<?php

return [
    'eyebrow' => 'Ljudi iza RE-MIND-a',
    'title' => 'KONZORCIJ',
    'contact_label' => 'Kontakt',
    'back_to_consortium' => 'Natrag na Konzorcij',
    'intro_title' => 'SNAŽNO EUROPSKO PARTNERSTVO',
    'intro_paragraph' => 'RE-MIND okuplja 11 partnerskih organizacija iz 7 europskih zemalja, ujedinjenih zajedničkom predanošću stvaranju svjesnijih, inkluzivnijih i angažiranijih muzejskih iskustava. Kroz prekograničnu suradnju, partneri iz Srbije, Italije, Hrvatske, Poljske, Slovenije, Bosne i Hercegovine te Sjeverne Makedonije doprinose svojom stručnošću, znanjem i kulturnim perspektivama poticanju inovacija i trajnog utjecaja diljem europskog muzejskog sektora.',

    'partners' => [
        'mei' => [
            'name' => 'MEI – Minds Europe – Institute for Research Excellence and Technological Advancement',
            'bio' => [
                'Minds Europe – Institute for Research Excellence and Technological Advancement (MEI) je nevladina i neprofitna organizacija za istraživanje i razvoj sa sjedištem u Novom Sadu, Srbija, osnovana 2020. godine. Djelujući kroz četiri strateška stupa - Mind-set KULTURA, PRIRODA, LJUDI i AI - MEI povezuje akademsku izvrsnost s praktičnim društvenim inovacijama. Organizacija djeluje na sjecištu kulture, obrazovanja, digitalne transformacije, dobrobiti i inkluzivnog angažmana zajednice, razvijajući metodologije utemeljene na istraživanju, obrazovne programe i inovativna rješenja koja podržavaju održivi društveni razvoj i jačaju kapacitete kulturnih i obrazovnih institucija.',
                'Kao koordinator projekta RE-MIND, MEI vodi Radni paket 1: Upravljanje projektom i koordinacija, osiguravajući učinkovitu provedbu, financijsko upravljanje, osiguranje kvalitete i cjelokupno strateško usmjeravanje projekta. MEI također vodi razvoj Nacrta svjesnog muzeja (Mindful Museum Blueprint) unutar Radnog paketa 2 te pridonosi dizajnu programa obuke, obrazovnih resursa, međugeneracijskih radionica, prezentacijskih događanja (Showroom Events) i Kulturnih krugova (Culture Circles). Organizacija ima središnju ulogu u integraciji rezultata istraživanja u praktične alate za muzeje diljem Europe.',
                'MEI spaja ekspertizu u području usredotočene svjesnosti, digitalne dobrobiti, smirene tehnologije, sudjelovanja u kulturi, obrazovanja, ICT-a i interakcije čovjeka i računala. Organizacija razvija metodologije utemeljene na dokazima koje znanstvena istraživanja pretvaraju u praktična rješenja za kulturna i obrazovna okruženja. S opsežnim iskustvom u interdisciplinarnom istraživanju, izgradnji kapaciteta, digitalnom učenju i inovacijama, MEI podržava organizacije u stvaranju inkluzivnih, angažirajućih i digitalno uravnoteženih okruženja uz promicanje dobrobiti i cjeloživotnog učenja.',
                'MEI je koordinirao i sudjelovao u brojnim europskim projektima financiranim kroz programe Kreativna Europa, Obzor Europa, Erasmus+ i IPA. Njezino iskustvo uključuje izgradnju kapaciteta, digitalno obrazovanje, sudjelovanje u kulturi, angažman dionika, procjenu učinka i inovacije. Organizacija je također pridonijela velikim međunarodnim inicijativama evaluacije, uključujući Expo 2020 Dubai i Novi Sad – Europska prijestolnica kulture.',
            ],
        ],
        'algebra' => [
            'name' => 'Sveučilište Algebra Bernays',
            'bio' => [
                'Sveučilište Algebra Bernays jedna je od vodećih hrvatskih privatnih visokoškolskih institucija i dio najveće privatne obrazovne organizacije u zemlji i regiji, koja od svog osnutka 1998. godine djeluje u više od 20 gradova. Sveučilište je predano stvaranju inovativnog okruženja za učenje koje osnažuje studente, istraživače i stručnjake da postanu lideri u razvoju i primjeni digitalnih tehnologija. Njezina je vizija obrazovati etične inovatore i buduće pokretače promjena koji pridonose tehnološkom napretku i održivom društvenom razvoju.',
                'Unutar projekta RE-MIND, Sveučilište Algebra Bernays vodi Radni paket 3: Izgradnja RE-MIND pametnog ekosustava učenja za mikrokredencijale i institucionalnu podršku. Sveučilište je odgovorno za dizajn i razvoj projektnog digitalnog sustava za učenje, podržavanje integracije materijala za obuku u interaktivno online okruženje te doprinos razvoju okvira za mikrokredencijale. Također sudjeluje u provedbi projekta, aktivnostima validacije i širenju rezultata projekta.',
                'Sveučilište Algebra Bernays prepoznato je po svom multidisciplinarnom pristupu obrazovanju usmjerenom na studenta te po snažnoj ekspertizi u digitalnom učenju, instruktivnom dizajnu i STEM području. Sveučilište razvija inovativne obrazovne programe i integrira napredne metode poučavanja, uključujući poslovne simulacije i interaktivne tehnologije učenja. Svojom bliskom suradnjom s industrijskim partnerima i opsežnim iskustvom u projektima digitalne transformacije, Sveučilište pruža stručnost potrebnu za razvoj visokokvalitetnih okruženja za učenje i podršku inovacijama u obrazovanju i stručnom usavršavanju.',
                'Sveučilište Algebra Bernays ima bogato iskustvo u razvoju i implementaciji rješenja za digitalno obrazovanje i e-učenje za organizacije iz javnog i privatnog sektora. Sveučilište je uspješno realiziralo projekte usmjerene na instrukcijski dizajn, digitalnu transformaciju, mikrokredencijale i cjeloživotno učenje, kombinirajući ekspertizu u STEM-u, obrazovnim tehnologijama i inovativnim metodologijama učenja kako bi podržalo profesionalni razvoj u različitim sektorima.',
            ],
        ],
        'adm' => [
            'name' => 'Archivio della Memoria (AdM)',
            'bio' => [
                'Archivio della Memoria (AdM) je talijanska neprofitna kulturna organizacija osnovana 2002. godine sa sjedištem u Rimu. Organizacija je specijalizirana za očuvanje i promociju kulturne baštine pomoću digitalnih tehnologija, usmene povijesti, audiovizualnog pripovijedanja i participativnih edukativnih pristupa. Od 2006. godine AdM surađuje sa Sveučilištem Tor Vergata u Rimu te je dio mreže Znanstvenog parka Tor Vergata. Kroz istraživanja, obuke i inicijative za podizanje svijesti, AdM surađuje sa školama, sveučilištima, kulturnim institucijama i lokalnim zajednicama u svrhu promicanja cjeloživotnog učenja, socijalne inkluzije, dobrobiti i aktivnog sudjelovanja u kulturi.',
                'Archivio della Memoria vodi Radni paket 2 unutar projekta RE-MIND: Razvoj modela edukacije i dosega svjesnog muzeja te priručnika za obuku. Organizacija koordinira identifikaciju najboljih praksi, razvija RE-MIND priručnik za obuku i multimedijske resurse za učenje te pridonosi aktivnostima izgradnje kapaciteta za muzejske stručnjake. AdM također podržava edukativne sesije, međugeneracijske radionice i aktivnosti širenja rezultata, pomažući u promicanju svjesnih, inkluzivnih i digitalno uravnoteženih muzejskih iskustava.',
                'Archivio della Memoria posjeduje veliku ekspertizu u kulturnoj baštini, digitalnom pripovijedanju, audiovizualnoj produkciji, participativnom istraživanju i obrazovnim inovacijama. Tijekom protekla dva desetljeća, organizacija je producirala oko 2.000 kvalitativnih video intervjua, kombinirajući usmenu povijest s metodologijama društvenog pripovijedanja. Njezin multidisciplinarni tim ima značajno iskustvo u razvoju programa obuke, multimedijskih obrazovnih resursa i kampanja za podizanje svijesti usmjerenih na digitalne inovacije, dobrobit, socijalnu inkluziju i međugeneracijsko učenje kroz nacionalne i europske inicijative.',
                'Archivio della Memoria sudjelovao je u brojnim europskim projektima u područjima obrazovanja odraslih, strukovnog obrazovanja i osposobljavanja, mladih, škola i kulturne baštine. Njezino iskustvo uključuje projekte kao što su CHART, DIST-SEED, Erasmediah, DataPro, ACCESS, DEED i SIATE, s fokusom na kulturnu baštinu, digitalnu svijest, mentalnu dobrobit, ekološku održivost, socijalnu uključenost i izgradnju kapaciteta kroz inovativne obrazovne metodologije.',
            ],
        ],
        'bmn' => [
            'name' => 'Balkan Museum Network',
            'bio' => [
                'Balkan Museum Network (BMN) je međunarodna mreža sa sjedištem u Sarajevu, Bosna i Hercegovina, koja okuplja muzejske stručnjake i institucije iz više od 20 zemalja. Utemeljena kao regionalni program muzejske suradnje 2006. godine, a formalno registrirana kao udruga 2015. godine, BMN je narasla s 11 muzeja osnivača na mrežu od preko 150 muzeja članova i 300 stručnjaka za baštinu. BMN promovira suradnju, razmjenu znanja i profesionalni razvoj dok istovremeno slavi, čuva i dijeli bogatu i raznoliku kulturnu baštinu Balkana.',
                'BMN vodi Radni paket 5 unutar projekta RE-MIND: Implementacija i validacija modela izgradnje kapaciteta svjesnog muzeja te pridonosi svim ostalim radnim paketima. BMN koordinira organizaciju RE-MIND prezentacijskih događanja (Showroom Events), priznavanje RE-MIND ambasadora i sustav muzejske podrške, validaciju Modela svjesnog muzeja te konačnu doradu edukativnog i outreach okvira. Pomoću svoje široke muzejske mreže BMN podržava vidljivost, usvajanje i dugoročnu održivost projekta.',
                'BMN je vodeća regionalna platforma za jačanje muzejske prakse pomoću izgradnje kapaciteta, umrežavanja i suradničkih projekata. Od 2010. godine podržala je više od 100 muzejskih inicijativa, a trenutno upravlja Fondom za kulturnu baštinu Headley Southeast Europe, ulažući u zaštitu baštine diljem regije. BMN također promiče pristupačnost i inkluziju kroz svoju online bazu podataka pristupačnih muzejskih usluga, objavila je 28 stručnih publikacija, organizirala 12 međunarodnih putujućih muzejskih konferencija te uspostavila prestižne nagrade kojima se odaje priznanje za izvrsnost u muzejskoj praksi i promociji kulturne baštine.',
                'BMN ima veliko iskustvo u europskim projektima suradnje usmjerenim na pristupačnost, inkluziju i profesionalni razvoj u sektoru kulturne baštine. Pomoću svoje Balkanske skupine za pristup muzejima (BMAG) podržava muzeje da postanu pristupačniji i inkluzivniji. BMN je sudjelovao u Erasmus+ projektima kao što su Tomimeus i iNCLUSION, kao i u projektu SHIFT u sklopu programa Obzor, pridonoseći ekspertizom u izgradnji kapaciteta, umrežavanju i angažmanu publike.',
            ],
        ],
        'cwep' => [
            'name' => 'CWEP',
            'bio' => [
                'Centrum Wspierania Edukacji i Przedsiębiorczości (CWEP) je nevladina organizacija osnovana 2004. godine sa sjedištem u Rzeszówu, Poljska. CWEP je posvećen promicanju inovativnog obrazovanja, poduzetništva, znanstvenih istraživanja i održivog razvoja. Organizacija potiče cjeloživotno učenje, socijalnu inkluziju i inovacije stvaranjem pristupačnih obrazovnih prilika za ljude svih dobnih skupina. CWEP svojim radom osnažuje pojedince i zajednice znanjem i vještinama potrebnim za prihvaćanje digitalne transformacije, jačanje zapošljivosti, podršku odgovornom poduzetništvu i doprinos održivijem i inkluzivnijem društvu.',
                'CWEP vodi Radni paket 4 unutar projekta RE-MIND: Obrazovanje i međugeneracijski angažman publike u svjesnim muzejskim iskustvima. Organizacija je odgovorna za razvoj smjernica za angažman publike (Audience Engagement Guidance), osmišljavanje edukativnih sesija prilagođenih različitim generacijama te koordinaciju međugeneracijskih krugova učenja. U suradnji sa svim projektnim partnerima, CWEP pridonosi jačanju digitalne dobrobiti, usredotočene svjesnosti i socijalne inkluzije stvaranjem angažirajućih iskustava učenja koja podržavaju implementaciju RE-MIND modela svjesnog muzeja.',
                'CWEP ima bogato iskustvo u razvoju obrazovnih programa, provođenju obuka i implementaciji europskih projekata usmjerenih na digitalne vještine, poduzetništvo, socijalnu inkluziju i održivost. Organizacija kombinira ekspertizu u istraživanju, razvoju kurikuluma, izdavaštvu i komunikaciji kako bi stvorila inovativne resurse za učenje za različite ciljne skupine. Kroz brojne nacionalne i međunarodne inicijative, CWEP se etablirao kao pouzdan partner u promicanju cjeloživotnog učenja, digitalnih inovacija i inkluzivnog obrazovanja uz podršku razvoju vještina za budućnost.',
                'CWEP je sudjelovao u brojnim projektima financiranim od strane EU koji se bave digitalnim obrazovanjem, inkluzijom i cjeloživotnim učenjem. Njezino nedavno iskustvo uključuje projekte MYCo, DIST-SEED, Mindfulness for Integration i SOURCE, s fokusom na međugeneracijsku suradnju, digitalno pripovijedanje, obrazovanje temeljeno na usredotočenoj svjesnosti i inovativne metodologije poučavanja. Ovi projekti pokazuju snažnu stručnost CWEP-a u razvoju obrazovnih resursa, programa za izgradnju kapaciteta i inkluzivnih pristupa učenju.',
            ],
        ],
        'koda' => [
            'name' => 'Koda',
            'bio' => [
                'Koda je organizacija civilnog društva sa sjedištem u Ljubljani, Slovenija, specijalizirana za digitalnu kulturu, etičku upotrebu tehnologije i inkluzivni digitalni angažman. Svojim virtualnim izložbama, digitalnim kampanjama i hibridnim kulturnim iskustvima, Koda promiče cjeloživotno učenje i osnažuje pojedince za navigaciju digitalnim svijetom s povjerenjem, kreativnošću i kritičkom sviješću. Organizacija djeluje na sjecištu kulture, obrazovanja i tehnologije, potičući odgovorno digitalno sudjelovanje i podržavajući inovacije koje su pristupačne, etične i društveno inkluzivne.',
                'Unutar projekta RE-MIND, Koda vodi aktivnosti Osiguranja kvalitete, etike i evaluacije, osiguravajući da provedba projekta ostane usklađena sa standardima kvalitete, etičkim načelima i ciljevima projekta. Organizacija razvija okvir za osiguranje kvalitete, etiku i evaluaciju, dok također pridonosi razvoju RE-MIND priručnika za obuku, obrazovnih resursa i aktivnosti učenja. Kroz svoju ekspertizu u digitalnoj dobrobiti i odgovornim inovacijama, Koda podržava isporuku visokokvalitetnih i inkluzivnih rezultata projekta.',
                'Koda posjeduje opsežnu ekspertizu u digitalnoj kulturi, etičkoj tehnologiji, digitalnoj dobrobiti i inkluzivnom online sudjelovanju. Organizacija razvija inovativne obrazovne resurse, digitalne kampanje i participativne kulturne inicijative koje promoviraju odgovornu upotrebu tehnologije i digitalnu inkluziju. S bogatim iskustvom u upravljanju projektima, kreativnoj komunikaciji i kros-sektorskoj suradnji, Koda podržava cjeloživotno učenje i osnažuje pojedince i organizacije da se samouvjereno i etički angažiraju u digitalnim okruženjima, potičući pristupačne i društveno odgovorne inovacije.',
                'Koda ima veliko iskustvo u digitalnom obrazovanju, radu s mladima i izgradnji kapaciteta, s jakim naglaskom na digitalnu pismenost, online sigurnost, odgovornu upotrebu tehnologije i digitalnu dobrobit. Sudjelovanjem u nacionalnim i međunarodnim projektima, organizacija je razvila obrazovne resurse, provela obuke za mlade i stručnjake te implementirala inicijative koje promoviraju sigurno, inkluzivno i etičko digitalno sudjelovanje u različitim zajednicama.',
            ],
        ],
        'mov' => [
            'name' => 'Muzej Vojvodine (MoV)',
            'bio' => [
                'Muzej Vojvodine jedna je od vodećih kulturnih institucija u Srbiji, smješten u Novom Sadu, čije podrijetlo datira od Srpske narodne zbirke osnovane u Budimpešti 1847. godine. Posvećen očuvanju i interpretaciji bogate kulturne baštine regije Vojvodine, Muzej u svojim opsežnim zbirkama i izložbama dokumentira više od 8.000 godina ljudske povijesti. Predan služenju suvremenoj publici, Muzej promiče obrazovanje, inkluziju i cjeloživotno učenje, potičući posjetitelje na bolje razumijevanje prošlosti, dok istovremeno inspirira aktivan angažman u sadašnjosti i budućnosti.',
                'Unutar projekta RE-MIND, Muzej Vojvodine sudjeluje kao savjetodavni i pilot-partner, sudjelujući u svim projektnim aktivnostima. Muzej ima ključnu ulogu u radnim paketima 4 i 5, podržavajući aktivnosti angažmana publike te provedbu i validaciju modela izgradnje kapaciteta svjesnog muzeja. Zahvaljujući svojoj edukativnoj ekspertizi i bliskoj interakciji s različitim skupinama posjetitelja, Muzej pridonosi testiranju i usavršavanju inovativnih pristupa svjesnim, inkluzivnim i međugeneracijskim muzejskim iskustvima.',
                'Muzej Vojvodine kombinira veliku ekspertizu u arheologiji, etnologiji, povijesti i likovnoj umjetnosti sa snažnom predanošću muzejskoj edukaciji i angažmanu publike. Njezin multidisciplinarni tim kustosa, konzervatora, istraživača i muzejskih edukatora razvija inovativne izložbe i edukativne programe za posjetitelje svih dobnih skupina. Zahvaljujući aktivnom sudjelovanju u istraživačkim projektima, međunarodnim konferencijama i profesionalnim mrežama, Muzej pridonosi unapređenju muzejske prakse uz promicanje kulturne baštine kroz inkluzivna i angažirajuća iskustva učenja.',
                'Muzej Vojvodine ima bogato iskustvo u međunarodnoj suradnji sudjelujući u zajedničkim izložbama, istraživačkim inicijativama, programima kulturne razmjene i partnerstvima s muzejima i institucijama za baštinu diljem Europe. Ove su suradnje ojačale njegovu ekspertizu u angažmanu publike, interpretaciji baštine i provedbi projekata, potvrđujući njegovu ulogu aktivnog sudionika u međunarodnom kulturnom dijalogu i inovacijama u muzejskoj praksi.',
            ],
        ],
        'nimb' => [
            'name' => 'Nacionalna ustanova Zavod i muzej Bitola (NIMB)',
            'bio' => [
                'Nacionalna ustanova Zavod i muzej Bitola (NIMB) jedna je od vodećih institucija kulturne baštine u Sjevernoj Makedoniji, koja integrira zaštitu, istraživanje i prezentaciju materijalne i nematerijalne kulturne baštine. Sa sjedištem u Bitoli, institucija zapošljava multidisciplinarni tim arheologa, etnologa, povjesničara, povjesničara umjetnosti, konzervatora i muzejskih stručnjaka. Podržan od strane Ministarstva kulture Sjeverne Makedonije, NIMB svake godine provodi više od 50 nacionalnih i međunarodnih projekata, promovirajući očuvanje baštine, muzejsku edukaciju, pristupačnost i javni angažman za raznoliku publiku.',
                'Unutar projekta RE-MIND, NIMB sudjeluje kao demonstracijski i pilot-partner, pridonoseći implementaciji i validaciji Modela svjesnog muzeja. Institucija sudjeluje u svim projektnim aktivnostima, podržavajući razvoj obrazovnih resursa, stručno usavršavanje i interaktivne inicijative za angažman publike. Pilotiranjem pristupa temeljenih na usredotočenoj svjesnosti u muzejskom okruženju, NIMB pomaže u procjeni učinkovitosti modela u poticanju digitalne dobrobiti, međugeneracijskog dijaloga i društveno odgovornih muzejskih iskustava.',
                'S više od 90 godina kontinuiranog rada, NIMB posjeduje veliku ekspertizu u muzejskoj edukaciji, pristupačnosti, interpretaciji kulturne baštine i međunarodnom upravljanju projektima. Institucija ima više od dva desetljeća iskustva u obrazovnom programiranju i više od deset godina predanog rada na poboljšanju pristupačnosti za raznoliku publiku. Svojim inkluzivnim izložbama, inovativnim edukativnim inicijativama i snažnim partnerstvima, NIMB promovira jednak pristup kulturnoj baštini uz unapređenje suvremenih muzejskih praksi i angažmana zajednice.',
                'NIMB godišnje provodi više od 50 projekata o zaštiti baštine, muzejskoj interpretaciji, edukaciji i pristupačnosti. Institucija upravlja značajnim lokalitetima kulturne baštine, uključujući Heraclea Lyncestis, te je vodila inicijative za pristupačnost, razvila međunarodno izlagane taktilne izložbe i opsežno surađivala s europskim partnerima. Kao aktivni član međunarodnih muzejskih mreža, NIMB primjenjuje europske standarde u očuvanju baštine, inkluziji i održivom kulturnom turizmu.',
            ],
        ],
        'spac' => [
            'name' => 'SPAC — Scuola nazionale del patrimonio e delle attività culturali',
            'bio' => [
                'Scuola nazionale del patrimonio e delle attività culturali (Scuola) je talijanska institucija sa sjedištem u Rimu, koju je 2015. godine osnovalo Ministarstvo kulture radi promicanja kontinuiranog profesionalnog razvoja stručnjaka u području kulturne baštine. Kao međunarodni centar za obuku, istraživanje i inovacije, Scuola podržava transformaciju kulturnog sektora kroz interdisciplinarno učenje, primijenjena istraživanja i međunarodnu suradnju. Njezin rad je usmjeren na upravljanje baštinom, digitalnu transformaciju, pristupačnost i inkluziju, poticanje razmjene znanja i jačanje profesionalnih kapaciteta unutar ekosustava kulturne baštine.',
                'Unutar projekta RE-MIND, Scuola sudjeluje kao demonstracijski i pilot-partner, pridonoseći sukreiranju, provedbi, testiranju i validaciji modela izgradnje kapaciteta svjesnog muzeja. Organizacija je aktivno uključena u operativne radne pakete projekta, podržavajući programe obuke, radionice i aktivnosti validacije. Scuola također pridonosi širenju rezultata i angažmanu dionika kroz svoje široke nacionalne i međunarodne mreže te koordinira organizaciju RE-MIND prezentacijskog događaja (Showroom Event) u Italiji.',
                'Scuola posjeduje bogatu ekspertizu u osmišljavanju i provođenju programa profesionalnog razvoja za stručnjake iz muzeja, arhiva, knjižnica i kulturne baštine. Razvija inovativne prilike za učenje kroz formate uživo, online i u mješovitom obliku, podržavajući muzejske menadžere, javne dužnosnike, donositelje politika i praktičare u području baštine. Blisko surađujući s talijanskim Ministarstvom kulture i međunarodnim organizacijama, Scuola je izgradila snažnu stručnost u upravljanju baštinom, digitalnoj transformaciji, pristupačnosti, međunarodnoj suradnji i cjeloživotnom učenju, pomažući u jačanju kulturnog sektora kroz razmjenu znanja i izgradnju kapaciteta.',
                'Scuola je sudjelovala u brojnim europskim i međunarodnim inicijativama usmjerenim na razvoj vještina u kulturnoj baštini i inovacije, uključujući projekt CHARTER Erasmus+ Blueprint, suradnju u okviru programa Obzor Europa te Dicolab, talijanski nacionalni program za digitalne vještine u kulturnom sektoru. Također provodi međunarodne programe izgradnje kapaciteta za stručnjake za baštinu i upravlja platformom za digitalno učenje koja opslužuje više od 34.000 korisnika.',
            ],
        ],
        'tmnt' => [
            'name' => 'Tehnički muzej Nikola Tesla (TMNT)',
            'bio' => [
                'Tehnički muzej Nikola Tesla (TMNT) nalazi se u Zagrebu, Hrvatska, a osnovan je 1954. godine kao vodeći muzej u zemlji posvećen znanosti, tehnologiji i industrijskoj baštini. Smješten u prepoznatljivom arhitektonskom kompleksu koji je projektirao renomirani hrvatski arhitekt Marijan Haberle, muzej čuva i prezentira hrvatsku znanstvenu i tehnološku baštinu kroz inovativne izložbe i edukativne programe. Kao jedan od najposjećenijih muzeja u zemlji, TMNT aktivno promiče cjeloživotno učenje, javni angažman i interdisciplinarnu suradnju, stvarajući interaktivna iskustva koja povezuju znanost, kulturu i društvo.',
                'Unutar projekta RE-MIND, TMNT sudjeluje kao savjetodavni i pilot-partner, pridonoseći svim projektnim aktivnostima. Muzej ima aktivnu ulogu u inicijativama za angažman publike te podržava implementaciju i validaciju modela izgradnje kapaciteta svjesnog muzeja unutar Radnih paketa 4 i 5. Testiranjem inovativnih edukativnih pristupa i angažiranjem različitih skupina posjetitelja, TMNT pridonosi razvoju svjesnih, inkluzivnih i digitalno uravnoteženih muzejskih iskustava.',
                'TMNT čuva zbirku od više od 11.000 artefakata kulturne baštine te ima dugogodišnju ekspertizu u muzejskoj edukaciji, javnom angažmanu i znanstvenoj komunikaciji. Muzej razvija inovativne edukativne programe u partnerstvu sa sveučilištima, znanstvenim centrima, nevladinim organizacijama i stručnjacima iz područja znanosti, umjetnosti i humanističkih znanosti. Kao suorganizator Festivala znanosti u Hrvatskoj, TMNT je prepoznat po promicanju interdisciplinarnog učenja, povezivanju znanosti s kulturom i razvoju naprednih muzejskih iskustava koja odgovaraju na evoluirajuće potrebe društva.',
                'TMNT je proveo brojne nacionalne i međunarodne projekte koji promoviraju socijalnu inkluziju, javni angažman, rodnu ravnopravnost i sudjelovanje manjinskih skupina. Muzej aktivno podržava interdisciplinarne pristupe interpretaciji baštine i surađuje s europskim partnerima u međunarodnim mrežama i inicijativama financiranim od strane EU, pridonoseći inovacijama u muzejskoj edukaciji, pristupačnosti i razvoju publike.',
            ],
        ],
        'brainster' => [
            'name' => 'Brainster',
            'bio' => [
                'Brainster je vodeća organizacija za obrazovnu tehnologiju (EdTech) sa sjedištem u Skoplju, Sjeverna Makedonija, osnovana 2015. godine. Kroz praktično obrazovanje vođeno potrebama industrije, Brainster osnažuje pojedince vještinama za budućnost u IT-ju, umjetnoj inteligenciji, digitalnom marketingu, dizajnu i poduzetništvu. Organizacija je educirala više od 14.000 polaznika te je razvila inovativna rješenja za digitalno učenje, uključujući vlastiti sustav za upravljanje učenjem (LMS) i platformu za učenje pokretanu umjetnom inteligencijom.',
                'U projektu RE-MIND, Brainster vodi Radni paket 6: komunikacija, širenje rezultata i održivosti, nadzirući komunikacijsku strategiju projekta, vizualni identitet, web stranicu, društvene medije i angažman dionika. Brainster također pridonosi razvoju pametnog ekosustava učenja podržavajući okvir za mikrokredencijale i institucionalnu podršku. S bogatim iskustvom u digitalnom obrazovanju, tehnologijama učenja, komunikacijskim kampanjama i projektima europske suradnje, Brainster osigurava da rezultati projekta ostvare široku vidljivost, dugoročnu održivost i značajan učinak diljem Europe.',
            ],
        ],
    ],
];
