<?php

return [
    'eyebrow' => 'Ludzie stojący za RE-MIND',
    'title' => 'KONSORCJUM',
    'contact_label' => 'Kontakt',
    'back_to_consortium' => 'Powrót do Konsorcjum',
    'intro_title' => 'SILNE EUROPEJSKIE PARTNERSTWO',
    'intro_paragraph' => 'RE-MIND łączy 11 organizacji partnerskich z 7 krajów europejskich, zjednoczonych wspólnym zaangażowaniem w tworzenie bardziej świadomych, inkluzywnych i angażujących doświadczeń muzealnych. Dzięki transgranicznej współpracy partnerzy z Serbii, Włoch, Chorwacji, Polski, Słowenii, Bośni i Hercegowiny oraz Macedonii Północnej wnoszą swoją wiedzę, doświadczenie i perspektywy kulturowe, aby napędzać innowacje i trwały wpływ w europejskim sektorze muzealnym.',

    'partners' => [
        'mei' => [
            'name' => 'MEI – Minds Europe – Institute for Research Excellence and Technological Advancement',
            'bio' => [
                'Minds Europe - Institute for Research Excellence and Technological Advancement (MEI) to pozarządowa organizacja badawczo-rozwojowa non-profit z siedzibą w Nowym Sadzie w Serbii, założona w 2020 roku. Działając w oparciu o cztery strategiczne filary - Mind-set CULTURE, NATURE, PEOPLE oraz AI - MEI łączy doskonałość akademicką z praktycznymi innowacjami społecznymi. Organizacja działa na styku kultury, edukacji, transformacji cyfrowej, dobrostanu i włączającego zaangażowania społeczności, opracowując oparte na badaniach metodologie, programy edukacyjne oraz innowacyjne rozwiązania, które wspierają zrównoważony rozwój społeczny i wzmacniają potencjał instytucji kultury oraz placówek edukacyjnych.',
                'Jako koordynator projektu RE-MIND, MEI kieruje Pakietem Roboczym 1: Zarządzanie i Koordynacja Projektu, zapewniając skuteczną realizację, zarządzanie finansami, zapewnienie jakości oraz ogólny kierunek strategiczny projektu. MEI kieruje również opracowaniem Planu Uważnego Muzeum (Mindful Museum Blueprint) w ramach Pakietu Roboczego 2 oraz przyczynia się do projektowania programu szkoleniowego, zasobów edukacyjnych, warsztatów międzypokoleniowych, Wydarzeń Pokazowych (Showroom Events) i Kręgów Kultury (Culture Circles). Organizacja odgrywa kluczową rolę w integracji wyników badań z praktycznymi narzędziami dla muzeów w całej Europie.',
                'MEI łączy wiedzę specjalistyczną z zakresu uważności, cyfrowego dobrostanu, spokojnej technologii (calm technology), uczestnictwa w kulturze, edukacji, technologii informacyjno-komunikacyjnych (ICT) oraz interakcji człowiek-komputer. Organizacja opracowuje oparte na dowodach metodologie, które przekładają badania naukowe na praktyczne rozwiązania dla środowisk kulturalnych i edukacyjnych. Dzięki bogatemu doświadczeniu w badaniach interdyscyplinarnych, budowaniu potencjału, edukacji cyfrowej i innowacjach, MEI wspiera organizacje w tworzeniu włączających, angażujących i zrównoważonych cyfrowo środowisk, promując jednocześnie dobrostan i uczenie się przez całe życie.',
                'MEI koordynowało i uczestniczyło w licznych projektach europejskich finansowanych w ramach programów Creative Europe, Horizon Europe, Erasmus+ oraz IPA. Jego doświadczenie obejmuje budowanie potencjału, edukację cyfrową, uczestnictwo w kulturze, angażowanie interesariuszy, ocenę wpływu oraz innowacje. Organizacja wniosła również wkład w ważne międzynarodowe inicjatywy ewaluacyjne, w tym Expo 2020 Dubai oraz Nowy Sad - Europejska Stolica Kultury.',
            ],
        ],
        'algebra' => [
            'name' => 'Algebra Bernays University',
            'bio' => [
                'Algebra Bernays University to jedna z wiodących prywatnych uczelni wyższych w Chorwacji i część największej prywatnej organizacji edukacyjnej w kraju i regionie, działającej w ponad 20 miastach od momentu jej założenia w 1998 roku. Uniwersytet jest zaangażowany w tworzenie innowacyjnego środowiska uczenia się, które umożliwia studentom, naukowcom i profesjonalistom stanięcie na czele rozwoju i wdrażania technologii cyfrowych. Jego wizją jest kształcenie etycznych innowatorów i przyszłych liderów zmian, którzy przyczyniają się do postępu technologicznego i zrównoważonego rozwoju społecznego.',
                'W ramach projektu RE-MIND, Algebra Bernays University kieruje Pakietem Roboczym 3: Budowanie Inteligentnego Ekosystemu Edukacyjnego RE-MIND na rzecz Mikropoświadczeń i Poparcia Instytucjonalnego. Uczelnia jest odpowiedzialna za projektowanie i rozwój cyfrowej platformy edukacyjnej projektu, wspieranie integracji materiałów szkoleniowych w interaktywnym środowisku online oraz wkład w opracowanie ram mikropoświadczeń. Uczestniczy również w realizacji projektu, działaniach walidacyjnych oraz upowszechnianiu rezultatów projektu.',
                'Algebra Bernays University jest ceniona za swoje multidyscyplinarne, skoncentrowane na studencie podejście do edukacji oraz silną wiedzę ekspercką w zakresie cyfrowej nauki, projektowania instruktażowego (instructional design) i nauk STEM. Uniwersytet opracowuje innowacyjne programy edukacyjne i integruje zaawansowane metody nauczania, w tym symulacje biznesowe oraz interaktywne technologie edukacyjne. Poprzez ścisłą współpracę z partnerami branżowymi i bogate doświadczenie w projektach transformacji cyfrowej, uczelnia zapewnia wiedzę niezbędną do tworzenia wysokiej jakości środowisk uczenia się oraz wspierania innowacji w edukacji i szkoleniu zawodowym.',
                'Algebra Bernays University posiada bogate doświadczenie w opracowywaniu i wdrażaniu rozwiązań z zakresu cyfrowej edukacji i e-learningu dla organizacji sektora publicznego i prywatnego. Uczelnia z powodzeniem zrealizowała projekty skoncentrowane na projektowaniu instruktażowym, transformacji cyfrowej, mikropoświadczeniach oraz uczeniu się przez całe życie, łącząc wiedzę z zakresu STEM, technologii edukacyjnych i innowacyjnych metodologii nauczania w celu wspierania rozwoju zawodowego w różnych sektorach.',
            ],
        ],
        'adm' => [
            'name' => 'Archivio della Memoria (AdM)',
            'bio' => [
                'Archivio della Memoria (AdM) to włoska organizacja kulturalna non-profit założona w 2002 roku z siedzibą w Rzymie. Organizacja specjalizuje się w ochronie i promocji dziedzictwa kulturowego poprzez technologie cyfrowe, historię mówioną, storytelling audiowizualny oraz partycypacyjne podejścia edukacyjne. Od 2006 roku AdM współpracuje z Uniwersytetem Tor Vergata w Rzymie i należy do sieci Parku Naukowego Tor Vergata. Poprzez inicjatywy badawcze, szkoleniowe i podnoszące świadomość, AdM współpracuje ze szkołami, uniwersytetami, instytucjami kultury oraz społecznościami lokalnymi, aby promować uczenie się przez całe życie, włączenie społeczne, dobrostan i aktywne uczestnictwo w kulturze.',
                'W ramach projektu RE-MIND, Archivio della Memoria kieruje Pakietem Roboczym 2: Opracowanie Modelu Edukacji i Dotarcia Uważnego Muzeum oraz Zestawu Narzędzi Szkoleniowych. Organizacja koordynuje identyfikację dobrych praktyk, opracowuje zestaw narzędzi szkoleniowych RE-MIND i multimedialne zasoby edukacyjne, a także przyczynia się do działań na rzecz budowania potencjału personelu muzeów. AdM wspiera również sesje edukacyjne, warsztaty międzypokoleniowe i działania upowszechniające, pomagając promować uważne, włączające i zrównoważone cyfrowo doświadczenia muzealne.',
                'AdM dysponuje bogatym doświadczeniem w dziedzinie dziedzictwa kulturowego, cyfrowego storytellingu, produkcji audiowizualnej, badań partycypacyjnych oraz innowacji edukacyjnych. W ciągu ostatnich dwóch dekad organizacja zrealizowała około 2000 jakościowych wywiadów wideo, łącząc historię mówioną z metodologią storytellingu społecznego. Jej multidyscyplinarny zespół posiada znaczące doświadczenie w opracowywaniu programów szkoleniowych, multimedialnych zasobów edukacyjnych oraz kampanii społecznych skoncentrowanych na innowacjach cyfrowych, dobrostanie, włączeniu społecznym i uczeniu się międzypokoleniowym w ramach inicjatyw zarówno krajowych, jak i europejskich.',
                'Archivio della Memoria uczestniczyło w licznych projektach europejskich w obszarach edukacji dorosłych, kształcenia i szkolenia zawodowego, młodzieży, szkół oraz dziedzictwa kulturowego. Jej doświadczenie obejmuje projekty takie jak CHART, DIST-SEED, Erasmediah, DataPro, ACCESS, DEED oraz SIATE, koncentrujące się na dziedzictwie kulturowym, świadomości cyfrowej, dobrostanie psychicznym, zrównoważonym rozwoju środowiskowym, włączeniu społecznym i budowaniu potencjału poprzez innowacyjne metodologie edukacyjne.',
            ],
        ],
        'bmn' => [
            'name' => 'Balkan Museum Network',
            'bio' => [
                'Balkan Museum Network (BMN) to międzynarodowa sieć z siedzibą w Sarajewie (Bośnia i Hercegowina), zrzeszająca muzealników i instytucje muzealne z ponad 20 krajów. Powstała w 2006 roku jako regionalny program współpracy muzeów, a w 2015 roku została formalnie zarejestrowana jako stowarzyszenie. BMN rozwinęła się z 11 muzeów założycielskich do sieci skupiającej ponad 150 muzeów członkowskich i 300 specjalistów ds. dziedzictwa. BMN promuje współpracę, wymianę wiedzy i rozwój zawodowy, jednocześnie celebrując, chroniąc i upowszechniając bogate i różnorodne dziedzictwo kulturowe Bałkanów.',
                'W ramach projektu RE-MIND, BMN kieruje Pakietem Roboczym 5: Wdrożenie i Walidacja Modelu Budowania Potencjału Uważnego Muzeum oraz wnosi wkład we wszystkie pozostałe pakiety pracy. BMN koordynuje organizację Wydarzeń Pokazowych RE-MIND (Showroom Events), wyłanianie Ambasadorów RE-MIND, system przyznawania wyróżnień „Uważne Muzeum” (Mindful Museum), walidację Modelu Uważnego Muzeum oraz ostateczne dopracowanie ram edukacyjnych i działań upowszechniających. Dzięki swojej rozległej sieci muzeów BMN wspiera widoczność, wdrażanie oraz długoterminową trwałość projektu.',
                'BMN jest wiodącą regionalną platformą wzmacniania praktyki muzealnej poprzez budowanie potencjału, networking i wspólne projekty. Od 2010 roku sieć wsparła ponad 100 inicjatyw muzealnych i obecnie zarządza funduszem Headley Southeast Europe Cultural Heritage Fund, inwestując w ochronę dziedzictwa w całym regionie. BMN promuje również dostępność i włączenie społeczne poprzez swoją internetową bazę danych dostępnych usług muzealnych. Ponadto sieć wydała 28 publikacji branżowych, zorganizowała 12 międzynarodowych objazdowych konferencji muzealnych oraz ustanowiła prestiżowe nagrody doceniające doskonałość w praktyce muzealnej i promocji dziedzictwa kulturowego.',
                'BMN posiada bogate doświadczenie w europejskich projektach współpracy skoncentrowanych na dostępności, włączeniu społecznym oraz rozwoju zawodowym w sektorze dziedzictwa kulturowego. Poprzez swoją grupę roboczą Balkan Museum Access Group (BMAG) wspiera muzea w stawaniu się bardziej dostępnymi i włączającymi. BMN uczestniczyła w projektach Erasmus+, takich jak Tomimeus i iNCLUSION, a także w projekcie SHIFT w ramach programu Horizon, wnosząc wiedzę ekspercką z zakresu budowania potencjału, networkingu oraz angażowania publiczności.',
            ],
        ],
        'cwep' => [
            'name' => 'CWEP',
            'bio' => [
                'Centrum Wspierania Edukacji i Przedsiębiorczości (CWEP) to organizacja pozarządowa założona w 2004 roku z siedzibą w Rzeszowie (Polska). CWEP jest zaangażowane w promowanie innowacyjnej edukacji, przedsiębiorczości, badań naukowych oraz zrównoważonego rozwoju. Organizacja wspiera uczenie się przez całe życie, włączenie społeczne i innowacje poprzez tworzenie dostępnych możliwości edukacyjnych dla osób w każdym wieku. Poprzez swoją pracę CWEP wyposaża jednostki i społeczności w wiedzę i umiejętności niezbędne do radzenia sobie z transformacją cyfrową, zwiększania szans na zatrudnienie, wspierania odpowiedzialnej przedsiębiorczości oraz przyczyniania się do budowy bardziej zrównoważonego i włączającego społeczeństwa.',
                'W ramach projektu RE-MIND, CWEP kieruje Pakietem Roboczym 4: Edukacja i Międzypokoleniowe Angażowanie Publiczności w Doświadczenia Uważnego Muzeum. Organizacja jest odpowiedzialna za opracowanie Wskazówek dotyczących angażowania publiczności, projektowanie sesji edukacyjnych dostosowanych do różnych pokoleń oraz koordynowanie międzypokoleniowych kręgów uczenia się. We współpracy ze wszystkimi partnerami projektu, CWEP przyczynia się do wzmacniania cyfrowego dobrostanu, uważności oraz włączenia społecznego poprzez tworzenie angażujących doświadczeń edukacyjnych wspierających wdrażanie Modelu Uważnego Muzeum RE-MIND.',
                'CWEP posiada bogate doświadczenie w opracowywaniu programów edukacyjnych, prowadzeniu szkoleń oraz realizacji projektów europejskich skoncentrowanych na umiejętnościach cyfrowych, przedsiębiorczości, włączeniu społecznym i zrównoważonym rozwoju. Organizacja łączy wiedzę specjalistyczną w zakresie badań, opracowywania programów nauczania, publikacji i komunikacji, aby tworzyć innowacyjne zasoby edukacyjne dla różnych grup docelowych. Dzięki licznym inicjatywom krajowym i międzynarodowym, CWEP ugruntowało swoją pozycję jako zaufany partner w promowaniu uczenia się przez całe życie, innowacji cyfrowych i edukacji włączającej.',
                'CWEP uczestniczyło w licznych projektach finansowanych ze środków UE, dotyczących edukacji cyfrowej, włączenia społecznego i uczenia się przez całe życie. Jego ostatnie doświadczenia obejmują projekty takie jak MYCo, DIST-SEED, Mindfulness for Integration oraz SOURCE, koncentrujące się na współpracy międzypokoleniowej, cyfrowym storytellingu, edukacji opartej na uważności oraz innowacyjnych metodologiach nauczania. Projekty te dowodzą silnej wiedzy eksperckiej CWEP w zakresie opracowywania zasobów edukacyjnych, programów budowania potencjału oraz włączających podejść do uczenia się.',
            ],
        ],
        'koda' => [
            'name' => 'Koda',
            'bio' => [
                'Koda to organizacja społeczeństwa obywatelskiego z siedzibą w Lublanie (Słowenia), specjalizująca się w kulturze cyfrowej, etycznym korzystaniu z technologii oraz włączającym zaangażowaniu cyfrowym. Poprzez wirtualne wystawy, kampanie cyfrowe i hybrydowe doświadczenia kulturalne, Koda promuje uczenie się przez całe życie oraz wyposaża jednostki w umiejętności niezbędne do poruszania się po cyfrowym świecie z pewnością siebie, kreatywnością i krytyczną świadomością. Organizacja działa na styku kultury, edukacji i technologii, wspierając odpowiedzialne uczestnictwo w środowisku cyfrowym oraz innowacje, które są dostępne, etyczne i włączające społecznie.',
                'W ramach projektu RE-MIND, Koda kieruje działaniami w zakresie Zapewnienia Jakości, Etyki i Ewaluacji, dbając o to, aby realizacja projektu była spójna ze standardami jakości, zasadami etycznymi oraz celami projektu. Organizacja opracowuje ramy zapewnienia jakości, etyki i ewaluacji, wnosząc jednocześnie wkład w tworzenie zestawu narzędzi szkoleniowych RE-MIND, zasobów edukacyjnych oraz działań związanych z uczeniem się. Dzięki swojej wiedzy specjalistycznej w dziedzinie cyfrowego dobrostanu i odpowiedzialnych innowacji, Koda wspiera dostarczanie wysokiej jakości i włączających rezultatów projektu.',
                'Koda dysponuje bogatą wiedzą ekspercką w zakresie kultury cyfrowej, etycznych technologii, cyfrowego dobrostanu oraz włączającego uczestnictwa online. Organizacja opracowuje innowacyjne zasoby edukacyjne, kampanie cyfrowe i partycypacyjne inicjatywy kulturalne, które promują odpowiedzialne korzystanie z technologii oraz włączenie cyfrowe. Dzięki dużemu doświadczeniu w zarządzaniu projektami, kreatywnej komunikacji i współpracy międzysektorowej, Koda wspiera uczenie się przez całe życie oraz umożliwia osobom i organizacjom pewne i etyczne funkcjonowanie w środowiskach cyfrowych, jednocześnie wspierając dostępne i społecznie odpowiedzialne innowacje.',
                'Koda posiada bogate doświadczenie w obszarach edukacji cyfrowej, pracy z młodzieżą oraz budowania potencjału, kładąc silny nacisk na piśmienność cyfrową, bezpieczeństwo online, odpowiedzialne korzystanie z technologii oraz cyfrowy dobrostan. Poprzez projekty krajowe i międzynarodowe organizacja opracowała zasoby edukacyjne, prowadziła szkolenia dla młodzieży i profesjonalistów, a także wdrażała inicjatywy promujące bezpieczne, włączające i etyczne uczestnictwo w świecie cyfrowym w różnych społecznościach.',
            ],
        ],
        'mov' => [
            'name' => 'Museum of Vojvodina (MoV)',
            'bio' => [
                'Museum of Vojvodina to jedna z wiodących instytucji kultury w Serbii z siedzibą w Nowym Sadzie, której początki sięgają Serbskiej Kolekcji Narodowej założonej w Budapeszcie w 1847 roku. Dedykowane ochronie i interpretacji bogatego dziedzictwa kulturowego regionu Wojwodiny, Muzeum dokumentuje ponad 8000 lat historii ludzkości poprzez swoje bogate zbiory i wystawy. Angażując się w służbę współczesnej publiczności, Muzeum promuje edukację, włączenie społeczne i uczenie się przez całe życie, zachęcając zwiedzających do lepszego zrozumienia przeszłości, jednocześnie inspirując do aktywnego zaangażowania w teraźniejszość i przyszłość.',
                'W ramach projektu RE-MIND, MoV uczestniczy jako partner doradczy i pilotażowy, biorąc udział we wszystkich działaniach projektu. Muzeum odgrywa kluczową rolę w Pakietach Roboczych 4 i 5, wspierając działania związane z angażowaniem publiczności oraz wdrożeniem i walidacją Modelu Budowania Potencjału Uważnego Muzeum. Dzięki swojej wiedzy edukacyjnej i bliskiej interakcji z różnorodnymi grupami zwiedzających, Muzeum przyczynia się do testowania i dopracowywania innowacyjnych podejść do uważnych, włączających i międzypokoleniowych doświadczeń muzealnych.',
                'MoV łączy bogatą wiedzę ekspercką z zakresu archeologii, etnologii, historii i sztuk pięknych z silnym zaangażowaniem w edukację muzealną i angażowanie publiczności. Jego multidyscyplinarny zespół kuratorów, konserwatorów, badaczy i edukatorów muzealnych opracowuje innowacyjne wystawy i programy edukacyjne dla zwiedzających w każdym wieku. Poprzez aktywny udział w projektach badawczych, międzynarodowych konferencjach i sieciach zawodowych, Muzeum przyczynia się do rozwoju praktyki muzealnej, promując jednocześnie dziedzictwo kulturowe poprzez włączające i angażujące doświadczenia edukacyjne.',
                'MoV posiada bogate doświadczenie w międzynarodowej współpracy poprzez wspólne wystawy, inicjatywy badawcze, programy wymiany kulturalnej oraz partnerstwa z muzeami i instytucjami dziedzictwa w całej Europie. Współpraca ta wzmocniła jego wiedzę specjalistyczną w zakresie angażowania publiczności, interpretacji dziedzictwa i realizacji projektów, umacniając jego rolę jako aktywnego uczestnika międzynarodowego dialogu kulturowego i innowacji w praktyce muzealnej.',
            ],
        ],
        'nimb' => [
            'name' => 'Instytucja Narodowa Instytut i Muzeum w Bitoli (NIMB)',
            'bio' => [
                'Instytucja Narodowa Instytut i Muzeum w Bitoli (National Institution Institute and Museum Bitola - NIMB) to jedna z wiodących instytucji dziedzictwa kulturowego w Macedonii Północnej, łącząca ochronę, badania oraz prezentację materialnego i niematerialnego dziedzictwa kulturowego. Mająca siedzibę w Bitoli instytucja zatrudnia multidyscyplinarny zespół archeologów, etnologów, historyków, historyków sztuki, konserwatorów oraz muzealników. Wspierana przez Ministerstwo Kultury Macedonii Północnej, NIMB realizuje rocznie ponad 50 projektów krajowych i międzynarodowych, promując ochronę dziedzictwa, edukację muzealną, dostępność oraz zaangażowanie różnorodnych grup odbiorców.',
                'W ramach projektu RE-MIND, NIMB uczestniczy jako partner demonstracyjny i pilotażowy, wnosząc wkład w realizację i walidację Modelu Uważnego Muzeum. Instytucja bierze udział we wszystkich działaniach projektu, wspierając rozwój zasobów edukacyjnych, szkolenia zawodowe oraz interaktywne inicjatywy angażujące publiczność. Poprzez pilotażowe wdrażanie podejść opartych na uważności w przestrzeni muzealnej, NIMB pomaga w ocenie skuteczności modelu we wspieraniu cyfrowego dobrostanu, dialogu międzypokoleniowego oraz społecznie wrażliwych doświadczeń muzealnych.',
                'Dzięki ponad 90-letniej nieprzerwanej działalności, NIMB posiada bogatą wiedzę ekspercką w zakresie edukacji muzealnej, dostępności, interpretacji dziedzictwa kulturowego oraz zarządzania projektami międzynarodowymi. Instytucja ma ponad dwudziestoletnie doświadczenie w tworzeniu programów edukacyjnych i ponad dziesięć lat dedykowanej pracy nad poprawą dostępności dla różnych grup odbiorców. Poprzez włączające wystawy, innowacyjne inicjatywy edukacyjne oraz silne partnerstwa, NIMB promuje równy dostęp do dziedzictwa kulturowego, jednocześnie rozwijając współczesne praktyki muzealne i zaangażowanie społeczności.',
                'NIMB realizuje rocznie ponad 50 projektów z zakresu ochrony dziedzictwa, interpretacji muzealnej, edukacji oraz dostępności. Instytucja zarządza ważnymi obiektami dziedzictwa kulturowego, w tym stanowiskiem Heraclea Lyncestis, a także kierowała inicjatywami na rzecz dostępności, opracowała prezentowane na arenie międzynarodowej wystawy dotykowe oraz szeroko współpracowała z partnerami europejskimi. Jako aktywny członek międzynarodowych sieci muzealnych, NIMB stosuje europejskie standardy w dziedzinie ochrony dziedzictwa, włączenia społecznego oraz zrównoważonej turystyki kulturowej.',
            ],
        ],
        'spac' => [
            'name' => 'SPAC — Scuola nazionale del patrimonio e delle attività culturali',
            'bio' => [
                'Scuola nazionale del patrimonio e delle attività culturali (Scuola) to włoska instytucja z siedzibą w Rzymie, założona w 2015 roku przez Ministerstwo Kultury w celu promowania stałego rozwoju zawodowego specjalistów w dziedzinie dziedzictwa kulturowego. Jako międzynarodowe centrum szkoleń, badań i innowacji, Scuola wspiera transformację sektora kultury poprzez interdyscyplinarne uczenie się, badania stosowane oraz współpracę międzynarodową. Jej działania koncentrują się na zarządzaniu dziedzictwem, transformacji cyfrowej, dostępności i włączeniu społecznym, wspierając wymianę wiedzy i wzmacniając potencjał zawodowy w całym ekosystemie dziedzictwa kulturowego.',
                'W ramach projektu RE-MIND, Scuola uczestniczy jako partner demonstracyjny i pilotażowy, wnosząc wkład we współtworzenie, wdrażanie, testowanie oraz walidację Modelu Budowania Potencjału Uważnego Muzeum. Organizacja jest aktywnie zaangażowana w operacyjne pakiety pracy projektu, wspierając programy szkoleniowe, warsztaty i działania walidacyjne. Scuola przyczynia się również do upowszechniania rezultatów i angażowania interesariuszy poprzez swoje rozległe sieci krajowe i międzynarodowe, a także koordynuje organizację Wydarzenia Pokazowego RE-MIND we Włoszech.',
                'Scuola posiada bogate doświadczenie w projektowaniu i realizowaniu programów rozwoju zawodowego dla pracowników muzeów, archiwów, bibliotek oraz instytucji dziedzictwa kulturowego. Opracowuje innowacyjne możliwości uczenia się w formatach stacjonarnych, online oraz hybrydowych, wspierając dyrektorów muzeów, urzędników publicznych, decydentów i praktyków dziedzictwa. Ściśle współpracując z włoskim Ministerstwem Kultury oraz organizacjami międzynarodowymi, Scuola zbudowała silną wiedzę ekspercką w zakresie zarządzania dziedzictwem, transformacji cyfrowej, dostępności, współpracy międzynarodowej i uczenia się przez całe życie.',
                'Scuola uczestniczyła w licznych europejskich i międzynarodowych inicjatywach koncentrujących się na rozwoju umiejętności i innowacjach w dziedzinie dziedzictwa kulturowego, w tym w projekcie CHARTER (Erasmus+ Blueprint), we współpracy w ramach programu Horizon Europe oraz w Dicolab - krajowym włoskim programie na rzecz umiejętności cyfrowych w sektorze kultury. Realizuje również międzynarodowe programy budowania potencjału dla specjalistów ds. dziedzictwa i zarządza cyfrową platformą edukacyjną obsługującą ponad 34 000 użytkowników.',
            ],
        ],
        'tmnt' => [
            'name' => 'Muzeum Techniczne Nikoli Tesli (TMNT)',
            'bio' => [
                'Muzeum Techniczne Nikoli Tesli (Technical Museum Nikola Tesla - TMNT) znajduje się w Zagrzebiu (Chorwacja). Zostało założone w 1954 roku jako wiodące muzeum w kraju poświęcone nauce, technologii oraz dziedzictwu przemysłowemu. Muzeum mieści się w zabytkowym kompleksie architektonicznym zaprojektowanym przez cenionego chorwackiego architekta Marijana Haberle. Instytucja ta chroni i prezentuje naukowe oraz technologiczne dziedzictwo Chorwacji poprzez innowacyjne wystawy i programy edukacyjne. Jako jedno z najczęściej odwiedzanych muzeów w kraju, TMNT aktywnie promuje uczenie się przez całe życie, zaangażowanie społeczne i współpracę interdyscyplinarną, tworząc interaktywne doświadczenia łączące naukę, kulturę i społeczeństwo.',
                'W ramach projektu RE-MIND, TMNT uczestniczy jako partner doradczy i pilotażowy, wnosząc wkład we wszystkie działania projektu. Muzeum odgrywa aktywną rolę w inicjatywach angażujących publiczność oraz wspiera wdrażanie i walidację Modelu Budowania Potencjału Uważnego Muzeum w ramach Pakietów Roboczych 4 i 5. Poprzez testowanie innowacyjnych podejść edukacyjnych i angażowanie różnorodnych grup zwiedzających, TMNT przyczynia się do rozwoju uważnych, włączających i zrównoważonych cyfrowo doświadczeń muzealnych.',
                'TMNT posiada w swoich zbiorach ponad 11 000 eksponatów dziedzictwa kulturowego i dysponuje wieloletnim doświadczeniem w edukacji muzealnej, angażowaniu publiczności oraz popularyzacji nauki. Muzeum opracowuje innowacyjne programy edukacyjne we współpracy z uniwersytetami, centrami nauki, organizacjami pozarządowymi oraz ekspertami z dziedzin nauki, sztuki i humanistyki. Jako współorganizator Festiwalu Nauki w Chorwacji, TMNT jest cenione za promowanie interdyscyplinarnego uczenia się, łączenie nauki z kulturą oraz rozwijanie nowoczesnych doświadczeń muzealnych odpowiadających na zmieniające się potrzeby społeczne.',
                'TMNT zrealizowało liczne projekty krajowe i międzynarodowe promujące włączenie społeczne, zaangażowanie publiczne, równość płci oraz uczestnictwo grup mniejszościowych. Muzeum aktywnie wspiera interdyscyplinarne podejścia do interpretacji dziedzictwa i współpracuje z europejskimi partnerami poprzez międzynarodowe sieci oraz inicjatywy finansowane ze środków UE, przyczyniając się do innowacji w edukacji muzealnej, dostępności i rozwoju publiczności.',
            ],
        ],
        'brainster' => [
            'name' => 'Brainster',
            'bio' => [
                'Brainster to wiodąca organizacja z obszaru technologii edukacyjnych (EdTech) z siedzibą w Skopje (Macedonia Północna), założona w 2015 roku. Poprzez praktyczną edukację dostosowaną do potrzeb rynku, Brainster wyposaża uczestników swoich szkoleń w umiejętności przyszłości z zakresu IT, sztucznej inteligencji, marketingu cyfrowego, projektowania i przedsiębiorczości. Organizacja przeszkoliła już ponad 14 000 osób i opracowała innowacyjne, cyfrowe rozwiązania edukacyjne, w tym własny system zarządzania nauczaniem (LMS) oraz platformę edukacyjną opartą na sztucznej inteligencji.',
                'W ramach projektu RE-MIND, Brainster kieruje Pakietem Roboczym 6: Komunikacja, Upowszechnianie i Trwałość, nadzorując strategię komunikacyjną projektu, jego identyfikację wizualną, stronę internetową, media społecznościowe oraz angażowanie interesariuszy. Brainster wnosi również wkład w rozwój Inteligentnego Ekosystemu Edukacyjnego, wspierając ramy mikropoświadczeń i poparcia instytucjonalnego. Dzięki bogatemu doświadczeniu w edukacji cyfrowej, technologiach edukacyjnych, kampaniach komunikacyjnych i europejskich projektach współpracy, Brainster dba o to, aby rezultaty projektu zyskały szeroką widoczność, długoterminową trwałość oraz znaczący wpływ w całej Europie.',
            ],
        ],
    ],
];
