<?php

return [
    'eyebrow' => 'The people behind RE-MIND',
    'title' => 'CONSORTIUM',
    'contact_label' => 'Contact',
    'back_to_consortium' => 'Back to Consortium',
    'intro_title' => 'A STRONG EUROPEAN PARTNERSHIP',
    'intro_paragraph' => 'RE-MIND brings together 11 partner organizations from 7 European countries, united by a shared commitment to creating more mindful, inclusive, and engaging museum experiences. Through cross-border collaboration, partners from Serbia, Italy, Croatia, Poland, Slovenia, Bosnia and Herzegovina, and North Macedonia contribute their expertise, knowledge, and cultural perspectives to drive innovation and lasting impact across Europe\'s museum sector.',

    'partners' => [
        'mei' => [
            'name' => 'MEI – Minds Europe – Institute for Research Excellence and Technological Advancement',
            'bio' => [
                'Minds Europe – Institute for Research Excellence and Technological Advancement (MEI) is a non-governmental, non-profit research and development organisation based in Novi Sad, Serbia, founded in 2020. Working across four strategic pillars — Mind-set, CULTURE, NATURE, PEOPLE and AI — MEI connects academic excellence with practical social innovation. The organisation operates at the intersection of culture, education, digital transformation, wellbeing, and inclusive community engagement, developing research-based methodologies, educational programmes, and innovative solutions that contribute to sustainable social development and strengthen the capacities of cultural and educational institutions.',
                'As coordinator of the RE-MIND project, MEI leads Work Package 1: Project Management and Coordination, ensuring efficient implementation, financial management, quality assurance, and overall strategic direction of the project. The organisation also coordinates the development of the Mindful Museum Blueprint within Work Package 2 and contributes to the design of the training programme, educational resources, intergenerational workshops, Showroom events, and Culture Circles. MEI plays a central role in translating research findings into practical tools for museums across Europe.',
                'MEI has expertise in mindfulness, digital wellbeing, calm technology, cultural participation, education, information and communication technologies (ICT), and human–computer interaction. The organisation develops evidence-based methodologies that turn scientific findings into practical solutions for cultural and educational settings. Thanks to long-standing experience in interdisciplinary research, capacity building, digital learning, and innovation, MEI helps organisations create inclusive, engaging, and digitally balanced environments, while promoting wellbeing and lifelong learning.',
                'MEI has coordinated and participated in numerous European projects funded through the Creative Europe, Horizon Europe, Erasmus+, and IPA programmes. Their experience spans capacity building, digital education, cultural participation, stakeholder engagement, impact assessment, and innovation. The organisation has also contributed to major international evaluation initiatives, including Expo 2020 Dubai and Novi Sad – European Capital of Culture.',
            ],
        ],
        'algebra' => [
            'name' => 'Algebra Bernays University',
            'bio' => [
                'Algebra Bernays University is one of the leading private higher education institutions in Croatia and part of the largest private educational organisation in the country and the region, operating in more than 20 cities since its founding in 1998. The University is committed to creating an innovative learning environment that equips students, researchers, and professionals to become leaders in the development and application of digital technologies. Its vision is to educate ethical innovators and future changemakers who will contribute to technological progress and sustainable social development.',
                'Within the RE-MIND project, Algebra Bernays University leads Work Package 3: Building the RE-MIND Smart Learning Ecosystem for micro-credentials and institutional recognition. The University is responsible for the design and development of the digital learning platform, the integration of training materials into an interactive online environment, and the development of the micro-credentials framework. It also actively participates in project implementation, validation activities, and the dissemination of project results.',
                'The University is recognised for its multidisciplinary, student-centred approach and its expertise in digital learning, instructional design, and STEM education. It develops innovative educational programmes and applies modern teaching methods, including business simulations and interactive learning technologies. Thanks to close cooperation with industry partners and extensive experience in digital transformation projects, the University provides expertise in developing high-quality learning environments and supporting innovation in education and professional training.',
                'Algebra Bernays University has long-standing experience in developing and implementing digital education and e-learning solutions for both the public and private sectors. The University has successfully delivered numerous projects in instructional design, digital transformation, micro-credentials, and lifelong learning, combining expertise in STEM, educational technologies, and innovative learning methodologies.',
            ],
        ],
        'adm' => [
            'name' => 'Archivio della Memoria (AdM)',
            'bio' => [
                'Archivio della Memoria (AdM) is an Italian non-profit cultural organisation founded in 2002 and based in Rome. The organisation specialises in preserving and promoting cultural heritage through digital technologies, oral history, audiovisual storytelling, and participatory educational approaches. Since 2006, AdM has collaborated with the University of Tor Vergata in Rome and is part of the Tor Vergata Science Park network. Through research, training, and awareness-raising activities, the organisation works with schools, universities, cultural institutions, and local communities, promoting lifelong learning, social inclusion, wellbeing, and active cultural participation.',
                'Within the RE-MIND project, Archivio della Memoria leads Work Package 2: Development of the education and audience-engagement model and the "Mindful Museum" Training Toolkit. The organisation coordinates the identification of good practices, develops the RE-MIND Training Toolkit and multimedia educational resources, as well as capacity-building activities for museum professionals. AdM also contributes to the delivery of educational sessions, intergenerational workshops, and dissemination activities, promoting mindful, inclusive, and digitally balanced museum experiences.',
                'The organisation has extensive experience in cultural heritage, digital storytelling, audiovisual production, participatory research, and educational innovation. Over the past two decades it has produced around 2,000 qualitative video interviews, combining oral history methodologies with social storytelling. Its multidisciplinary team has significant experience in developing training programmes, multimedia educational resources, and awareness-raising campaigns focused on digital innovation, wellbeing, social inclusion, and intergenerational learning.',
                'Archivio della Memoria has participated in numerous European projects in adult education, vocational education and training, youth, schools, and cultural heritage. Its experience includes projects such as CHART, DIST-SEED, Erasmediah, DataPro, ACCESS, DEED, and SIATE, focused on cultural heritage, digital literacy, mental wellbeing, environmental sustainability, social inclusion, and capacity building through innovative educational methodologies.',
            ],
        ],
        'bmn' => [
            'name' => 'Balkan Museum Network',
            'bio' => [
                'The Balkan Museum Network (BMN) is an international organisation based in Sarajevo, Bosnia and Herzegovina, successfully bringing together museum professionals and institutions in more than 20 countries. BMN was founded in 2006 as a regional programme for museum cooperation and was formally registered as an association in 2015. From 11 founding museums, BMN has grown into a network of more than 150 museums and 300 individual cultural heritage professionals. BMN continuously promotes cooperation, knowledge exchange, and professional development, while marking, protecting, and sharing the rich and diverse cultural heritage of the Balkans.',
                'Within the RE-MIND project, BMN leads Work Activity 5: Implementing and validating the Mindful Museum capacity-building model, and contributes to all other work activities. BMN coordinates the organisation of RE-MIND promotional events, the designation of RE-MIND Ambassadors and Mindful Museums, the validation of the Mindful Museum model, and the final refinement of the educational and communication framework. Through its extensive museum network, BMN contributes to the visibility, uptake, and long-term sustainability of the project.',
                'BMN is a leading regional platform for advancing museum practice through capacity building, networking, and joint project implementation. Since 2010, BMN has supported more than 100 museum initiatives, and currently manages the Headley Southeast Europe Cultural Heritage Fund, directly investing in the protection of cultural heritage across the region. BMN continuously promotes accessibility and inclusion through its online database of accessible museum services. It has also published 28 professional publications, organised 12 international travelling museum conferences, and established prestigious awards recognising excellence in museum practice and the promotion of cultural heritage.',
                'BMN has extensive experience collaborating on European projects focused on accessibility, inclusion, and professional development in the cultural heritage sector. Through its Balkan Museum Access Group (BMAG), it helps museums become more accessible and inclusive. BMN has participated in the Erasmus+ projects Tomimeus and iNCLUSION, as well as the Horizon project SHIFT, contributing its expertise in capacity building, networking, and public engagement.',
            ],
        ],
        'cwep' => [
            'name' => 'CWEP',
            'bio' => [
                'Centrum Wspierania Edukacji i Przedsiębiorczości (CWEP) is a non-governmental organisation founded in 2004 and based in Rzeszów, Poland. CWEP is dedicated to promoting innovative education, entrepreneurship, scientific research, and sustainable development. The organisation fosters lifelong learning, social inclusion, and innovation by creating accessible educational opportunities for people of all ages. Through its work, CWEP equips individuals and communities with the knowledge and skills needed to embrace digital transformation, strengthen employability, and support responsible entrepreneurship, contributing to a more sustainable and inclusive society.',
                'Within the RE-MIND project, CWEP leads Work Activity 4: Education and intergenerational public engagement in mindful museum experiences. The organisation is responsible for developing public engagement, designing educational programmes tailored to different generations, and coordinating intergenerational learning groups. In cooperation with all project partners, CWEP contributes to strengthening digital wellbeing, mindfulness, and social inclusion by creating engaging educational experiences that support the implementation of the RE-MIND Mindful Museum model.',
                'CWEP has long-standing experience in developing educational programmes, delivering training, and implementing European projects focused on digital skills, entrepreneurship, social inclusion, and sustainability. The organisation combines expertise in research, curriculum development, publishing, and communication to create innovative educational resources for diverse target groups. Through numerous national and international initiatives, CWEP has established itself as a trusted partner in promoting lifelong learning, digital innovation, and inclusive education, while supporting the development of future-ready skills.',
                "CWEP participates in numerous EU-funded projects focused on digital education, inclusion, and lifelong learning. Recent projects include MYCo, DIST-SEED, Mindfulness for Integration, and SOURCE, focusing on intergenerational cooperation, digital storytelling, mindfulness-based education, and innovative teaching methodologies. These projects confirm CWEP's strong expertise in developing educational resources, capacity-building programmes, and inclusive approaches to learning.",
            ],
        ],
        'koda' => [
            'name' => 'Koda',
            'bio' => [
                'Koda is a civil society organisation based in Ljubljana, Slovenia, specialising in digital culture, ethical use of technology, and inclusive digital participation. Through virtual exhibitions, digital campaigns, and hybrid cultural experiences, Koda promotes lifelong learning and empowers individuals to navigate the digital world creatively and critically. The organisation works at the intersection of culture, education, and technology, encouraging responsible digital participation and supporting innovations that are ethical, accessible, and socially inclusive.',
                "Within the RE-MIND project, Koda leads the Quality Control, Ethics, and Evaluation activities, ensuring that project implementation is consistent with quality standards, ethical principles, and project objectives. The organisation develops the quality assurance, ethics, and evaluation framework, while also contributing to the development of RE-MIND's training tools, educational resources, and learning activities. Through its expertise in digital wellbeing and responsible innovation, Koda contributes to delivering high-quality and inclusive project results.",
                'Koda has long-standing expertise in digital culture, ethical use of technology, digital wellbeing, and inclusive online learning. The organisation develops innovative educational resources, digital campaigns, and participatory cultural initiatives that promote responsible use of technology and digital inclusion. Through its extensive experience in project management, creative communication, and cross-sector cooperation, Koda supports lifelong learning and empowers individuals and organisations to engage confidently and ethically in digital environments, while fostering accessible and socially responsible innovation.',
                'Koda has extensive experience in digital education, youth work, and capacity building, with a strong focus on digital literacy, internet safety, responsible use of technology, and digital wellbeing. Through national and international projects, the organisation has developed educational resources, delivered training for young people and professionals, and implemented numerous initiatives promoting safe, inclusive, and ethical digital participation across different communities.',
            ],
        ],
        'mov' => [
            'name' => 'Museum of Vojvodina (MoV)',
            'bio' => [
                'The Museum of Vojvodina is one of the leading cultural institutions in Serbia, located in Novi Sad. Its roots trace back to the Serbian National Collection, founded in Budapest in 1847. Dedicated to preserving and interpreting the rich cultural heritage of the Vojvodina region, the Museum has documented more than 8,000 years of human history through its extensive collections and exhibitions. Committed to the needs of contemporary audiences, the Museum promotes education, inclusion, and lifelong learning, helping visitors better understand the past while inspiring them to actively engage with the present and the future.',
                'Within the RE-MIND project, the Museum of Vojvodina participates as an advisory and pilot partner, actively involved in all project activities. The Museum plays a key role in Work Activities 4 and 5, supporting public engagement activities as well as the implementation and validation of the Mindful Museum Capacity-Building Model. Through its expertise in museum education and close interaction with diverse visitor groups, the Museum contributes to testing and refining innovative approaches for creating mindful, inclusive, and multigenerational museum experiences.',
                'The Museum of Vojvodina brings together extensive expertise in archaeology, ethnology, history, and fine art, with a strong commitment to museum education and public engagement. Its multidisciplinary team of curators, conservators, researchers, and museum educators develops innovative exhibitions and educational programmes for visitors of all ages. Through active participation in research projects, international conferences, and professional networks, the Museum contributes to advancing museum practice, while promoting cultural heritage through inclusive and participatory learning.',
                'The Museum of Vojvodina has long-standing experience in international cooperation through joint exhibitions, research initiatives, cultural exchange programmes, and partnerships with museums and cultural heritage institutions across Europe. These collaborations have further strengthened its expertise in public engagement, cultural heritage interpretation, and project implementation, confirming its role as an active contributor to international cultural dialogue and innovation in museum practice.',
            ],
        ],
        'nimb' => [
            'name' => 'National Institution Institute and Museum – Bitola',
            'bio' => [
                'The National Institution Institute and Museum – Bitola is one of the leading cultural heritage protection institutions in North Macedonia, bringing together the protection, research, and presentation of tangible and intangible cultural heritage. Based in Bitola, the institution has a multidisciplinary team of archaeologists, ethnologists, historians, art historians, conservators, and museum professionals. With support from the Ministry of Culture and Tourism of North Macedonia, the Institute and Museum – Bitola carries out more than 50 national and international projects annually, promoting cultural heritage protection, museum education, accessibility, and active public engagement.',
                'Within the RE-MIND project, the Institute and Museum – Bitola participates as a demonstration and pilot partner, contributing to the implementation and validation of the Mindful Museum Model. The institution actively participates in all project activities, supporting the development of educational resources, professional training, and interactive public-engagement initiatives. By applying mindfulness-based approaches in a museum context, the institution contributes to evaluating the model\'s effectiveness in fostering digital wellbeing, intergenerational dialogue, and socially responsible museum experiences.',
                'With more than 90 years of continuous operation, the Museum has extensive experience in museum education, accessibility, cultural heritage interpretation, and international project management. The institution has more than two decades of experience developing and delivering educational programmes and more than a decade of dedicated work advancing accessibility for diverse target groups. Through inclusive exhibitions, innovative educational initiatives, and significant partnerships, the Institute and Museum – Bitola promotes equal access to cultural heritage, while contributing to the development of contemporary museum practice and active community engagement.',
                'The Institute and Museum – Bitola carries out more than 50 projects annually in the fields of cultural heritage protection, museum interpretation, education, and accessibility. The institution manages several significant cultural heritage sites, including Heraclea Lyncestis, and plays a leading role in accessibility initiatives, the development of tactile exhibitions (presented internationally), and cooperation with numerous European partners. As an active member of several international museum networks, the Museum applies European standards in cultural heritage protection, inclusion, and sustainable cultural tourism.',
            ],
        ],
        'spac' => [
            'name' => 'SPAC — Scuola nazionale del patrimonio e delle attività culturali',
            'bio' => [
                'Scuola nazionale del patrimonio e delle attività culturali (Scuola) is an Italian institution based in Rome, established in 2015 by the Italian Ministry of Culture to promote the continuous professional development of cultural heritage professionals. As an international centre for training, research, and innovation, Scuola supports the transformation of the cultural sector through interdisciplinary upskilling, applied research, and international cooperation. Its work focuses on cultural heritage management, digital transformation, accessibility, and inclusion, fostering knowledge exchange and strengthening professional capacities across the cultural heritage ecosystem.',
                'Within the RE-MIND project, Scuola participates as a presentation and pilot partner, contributing to the co-creation, implementation, testing, and validation of the Mindful Museum Capacity-Building Model. The organisation actively participates in the project\'s operational work activities, supporting training programmes, workshops, and validation activities. Scuola also contributes to knowledge dissemination and stakeholder engagement through its extensive national and international networks, as well as by coordinating the RE-MIND Showroom Event in Italy.',
                'Scuola has long-standing experience in creating and delivering professional development programmes for staff working in museums, archives, libraries, and cultural heritage protection institutions. It develops innovative learning opportunities through in-person, online, and blended formats aimed at museum managers, public officials, policymakers, and cultural heritage professionals. Working closely with the Italian Ministry of Culture and international organisations, Scuola has developed strong expertise in cultural heritage management, digital transformation, accessibility, international cooperation, and lifelong learning, contributing to strengthening the cultural sector through knowledge exchange and capacity building.',
                "The institution has participated in numerous European and international initiatives focused on skills development and innovation in the cultural heritage field, including the CHARTER Erasmus+ Blueprint project, collaborations within Horizon Europe, and Dicolab — Italy's national programme for digital skills development in the cultural sector. In addition, the institution runs international capacity-building programmes for cultural heritage professionals and manages a digital learning platform used by more than 34,000 users.",
            ],
        ],
        'tmnt' => [
            'name' => 'Nikola Tesla Technical Museum (TMNT)',
            'bio' => [
                "The Nikola Tesla Technical Museum (TMNT) is located in Zagreb, Croatia, and was founded in 1954 as the country's leading museum dedicated to science, technology, and industrial heritage. Housed in a distinctive architectural complex designed by renowned Croatian architect Marijan Haberle, it preserves and presents Croatia's scientific and technological history through innovative exhibitions and educational programmes. As one of the most visited museums in the country, TMNT actively promotes lifelong learning, public engagement, and interdisciplinary cooperation, creating interactive experiences that connect science, culture, and society.",
                'Within the RE-MIND project, TMNT participates as an advisory and pilot partner, contributing to all project activities. The Museum plays an active role in public-engagement initiatives and supports the implementation and validation of the Mindful Museum Capacity-Building Model within Work Activities 4 and 5. Through testing innovative educational approaches and actively engaging diverse visitor groups, TMNT contributes to the development of mindful, inclusive, and digitally balanced museum experiences.',
                'TMNT holds a collection of more than 11,000 cultural heritage objects and has long-standing experience in museum education, public engagement, and science communication. The Museum develops innovative educational programmes in partnership with universities, science centres, non-governmental organisations, and experts in the natural sciences, arts, and humanities. As co-organiser of the Science Festival in Croatia, TMNT is recognised for its role in promoting interdisciplinary learning, connecting science with culture, and developing contemporary museum experiences that respond to society\'s changing needs.',
                'TMNT has delivered numerous national and international projects promoting social inclusion, public engagement, gender equality, and the participation of minority groups. The Museum actively supports interdisciplinary approaches to cultural heritage interpretation and cooperates with European partners through international networks and EU-funded initiatives, contributing to innovation in museum education, accessibility, and audience development.',
            ],
        ],
        'brainster' => [
            'name' => 'Brainster',
            'bio' => [
                'Brainster is a leading education organisation in the field of technology, based in Skopje, North Macedonia, founded in 2015. Through practical, industry-driven education, Brainster equips individuals with future-ready skills in information technology, artificial intelligence, digital marketing, design, and entrepreneurship. The organisation has educated more than 14,000 students and developed innovative digital learning solutions, including its own Learning Management System (LMS) and an AI-based learning platform.',
                "Within the RE-MIND project, Brainster leads Work Activity 6 — Communication, knowledge dissemination, and sustainability, managing the project's communication strategy, visual identity, website, social media activities, and stakeholder engagement. Brainster also contributes to the development of the Smart Learning Ecosystem, supporting the micro-credentials and institutional recognition framework. Thanks to its extensive experience in digital education, educational technology, communication campaigns, and European cooperation projects, Brainster ensures the project's results achieve broad visibility, long-term sustainability, and significant impact across Europe.",
            ],
        ],
    ],
];
