<?php

return [
    'eyebrow' => 'Ljudi iza RE-MIND-a',
    'title' => 'KONZORCIJUM',
    'contact_label' => 'Kontakt',
    'back_to_consortium' => 'Nazad na konzorcijum',
    'intro_title' => 'SNAŽNO EVROPSKO PARTNERSTVO',
    'intro_paragraph' => 'RE-MIND okuplja 11 partnerskih organizacija iz 7 evropskih zemalja, ujedinjenih zajedničkom posvećenošću stvaranju svesnijih, inkluzivnijih i angažovanijih muzejskih iskustava. Kroz prekograničnu saradnju, partneri iz Srbije, Italije, Hrvatske, Poljske, Slovenije, Bosne i Hercegovine i Severne Makedonije doprinose svojom stručnošću, znanjem i kulturnim perspektivama podsticanju inovacija i trajnog uticaja širom evropskog muzejskog sektora.',

    'partners' => [
        'mei' => [
            'name' => 'MEI – Minds Europe – Institut za istraživačku izvrsnost i tehnološki napredak',
            'bio' => [
                'Minds Europe – Institut za istraživačku izvrsnost i tehnološki napredak (MEI) je nevladina, neprofitna organizacija za istraživanje i razvoj sa sedištem u Novom Sadu, osnovana 2020. godine. Delujući kroz četiri strateška stuba – Mind-set CULTURE, NATURE, PEOPLE i AI – MEI povezuje akademsku izvrsnost sa praktičnim društvenim inovacijama. Organizacija deluje na preseku kulture, obrazovanja, digitalne transformacije, blagostanja i inkluzivnog angažovanja zajednice, razvijajući metodologije zasnovane na istraživanjima, obrazovne programe i inovativna rešenja koja podržavaju održivi društveni razvoj i jačaju kapacitete kulturnih i obrazovnih institucija.',
                'Kao koordinator projekta RE-MIND, MEI vodi Radni paket 1 (RP1): Upravljanje projektom i koordinacija, obezbeđujući delotvornu realizaciju, finansijsko upravljanje, osiguranje kvaliteta i ukupno strateško usmerenje projekta. MEI takođe vodi razvoj Nacrta za model Mindful muzeja u okviru Radnog paketa 2 i doprinosi osmišljavanju programa obuke, obrazovnih resursa, međugeneracijskih radionica, prezentacionih događaja i Kulturnih krugova. Organizacija ima centralnu ulogu u pretvaranju rezultata istraživanja u praktične alate za muzeje širom Evrope.',
                'MEI objedinjuje stručnost u oblastima mindfulness pristupa, digitalnog blagostanja, calm tehnologije, kulturnog učešća, obrazovanja, informaciono-komunikacionih tehnologija (IKT-a) i interakcije čoveka i računara. Organizacija razvija metodologije zasnovane na dokazima koje naučna istraživanja pretvaraju u praktična rešenja za kulturna i obrazovna okruženja. Zahvaljujući bogatom iskustvu u interdisciplinarnim istraživanjima, izgradnji kapaciteta, digitalnom učenju i inovacijama, MEI podržava organizacije u stvaranju inkluzivnih, podsticajnih i digitalno uravnoteženih okruženja, uz promovisanje blagostanja i celoživotnog učenja.',
                'MEI koordinira i učestvuje u brojnim evropskim projektima finansiranim kroz programe Kreativna Evropa, Horizont Evropa, Erazmus+ i IPA. Iskustvo obuhvata izgradnju kapaciteta, digitalno obrazovanje, kulturno učešće, angažovanje zainteresovanih strana, procenu uticaja i inovacije. Organizacija je doprinela i velikim međunarodnim inicijativama evaluacije, uključujući Expo 2020 Dubai i Novi Sad – Evropsku prestonicu kulture.',
            ],
        ],
        'algebra' => [
            'name' => 'Algebra Bernays Univerzitet',
            'bio' => [
                'Algebra Bernays Univerzitet je jedna od vodećih privatnih visokoškolskih ustanova u Hrvatskoj i deo najveće privatne obrazovne organizacije u zemlji i regionu, koja od osnivanja 1998. godine posluje u više od 20 gradova. Univerzitet je posvećen stvaranju inovativnog okruženja za učenje koje osnažuje studente, istraživače i stručnjake da postanu predvodnici u razvoju i primeni digitalnih tehnologija. Njegova vizija je obrazovanje etičnih inovatora i budućih pokretača promena koji doprinose tehnološkom napretku i održivom razvoju društva.',
                'U okviru projekta RE-MIND, Algebra Bernays Univerzitet vodi Radni paket 3 (RP3): Izgradnja RE-MIND Pametnog ekosistema učenja za mikrokvalifikacije i institucionalno priznavanje. Univerzitet je odgovoran za projektovanje i razvoj projektne platforme za digitalno učenje, podršku integraciji materijala za obuku u interaktivno onlajn okruženje te doprinos razvoju okvira za mikrokvalifikacije. Takođe učestvuje u realizaciji projekta, aktivnostima validacije i diseminaciji projektnih rezultata.',
                'Algebra Bernays Univerzitet poznat je po multidisciplinarnom pristupu obrazovanju usmerenom na studente i snažnoj stručnosti u digitalnom učenju, nastavnom dizajnu i STEM oblastima. Univerzitet razvija inovativne obrazovne programe i primenjuje napredne nastavne metode, uključujući poslovne simulacije i interaktivne tehnologije učenja. Bliska saradnja sa industrijskim partnerima i bogato iskustvo u projektima digitalne transformacije omogućavaju Univerzitetu da obezbedi stručnost potrebnu za razvoj visokokvalitetnih okruženja za učenje i podršku inovacijama u obrazovanju i stručnom usavršavanju.',
                'Algebra Bernays Univerzitet ima veliko iskustvo u razvoju i primeni digitalnog obrazovanja i rešenja za elektronsko učenje u organizacijama javnog i privatnog sektora. Uspešno je realizovao projekte usmerene na nastavni dizajn, digitalnu transformaciju, mikrokvalifikacije i celoživotno učenje, kombinujući stručnost u STEM oblastima, obrazovnim tehnologijama i inovativnim metodologijama učenja.',
            ],
        ],
        'adm' => [
            'name' => 'Archivio della Memoria (AdM)',
            'bio' => [
                'Archivio della Memoria (AdM) je italijanska neprofitna kulturna organizacija osnovana 2002. godine sa sedištem u Rimu. Organizacija je specijalizovana za očuvanje i promovisanje kulturnog nasleđa putem digitalnih tehnologija, usmene istorije, audiovizuelnog pripovedanja i participativnih obrazovnih pristupa. Od 2006. godine AdM sarađuje sa Univerzitetom u Rimu Tor Vergata i deo je mreže Naučnog parka Tor Vergata. Kroz istraživanja, obuke i inicijative za podizanje svesti, AdM sarađuje sa školama, univerzitetima, kulturnim institucijama i lokalnim zajednicama radi promovisanja celoživotnog učenja, socijalne inkluzije, blagostanja i aktivnog kulturnog učešća.',
                'U okviru projekta RE-MIND, Archivio della Memoria vodi Radni paket 2 (RP2): Razvoj obrazovnog i promotivnog Mindful muzej modela i kompleta alata za obuku. Organizacija koordinira identifikovanje dobrih praksi, razvija RE-MIND komplet alata za obuku i multimedijalne resurse za učenje i doprinosi aktivnostima izgradnje kapaciteta muzejskih stručnjaka. AdM takođe podržava obrazovne sesije, međugeneracijske radionice i aktivnosti diseminacije, doprinoseći promovisanju mindful, inkluzivnih i digitalno uravnoteženih muzejskih iskustava.',
                'AdM poseduje veliko iskustvo u oblasti kulturnog nasleđa, digitalnog pripovedanja, audiovizuelne produkcije, participativnih istraživanja i obrazovnih inovacija. Tokom prethodne dve decenije organizacija je proizvela oko 2.000 kvalitativnih video-intervjua, kombinujući usmenu istoriju sa metodologijama društvenog pripovedanja. Njen multidisciplinarni tim ima značajno iskustvo u razvoju programa obuke, multimedijalnih obrazovnih resursa i kampanja za podizanje svesti usmerenih na digitalne inovacije, blagostanje, socijalnu inkluziju i međugeneracijsko učenje kroz nacionalne i evropske inicijative.',
                'Archivio della Memoria je učestvovao u brojnim evropskim projektima u oblastima obrazovanja odraslih, stručnog obrazovanja i osposobljavanja, mladih, škola i kulturnog nasleđa. Iskustvo obuhvata projekte CHART, DIST-SEED, Erasmediah, DataPro, ACCESS, DEED i SIATE, usmerene na kulturno nasleđe, digitalnu svest, mentalno blagostanje, ekološku održivost, socijalnu inkluziju i izgradnju kapaciteta kroz inovativne obrazovne metodologije.',
            ],
        ],
        'bmn' => [
            'name' => 'Balkanska mreža muzeja',
            'bio' => [
                'Balkanska mreža muzeja (BMN) je međunarodna mreža sa sedištem u Sarajevu, Bosna i Hercegovina, koja okuplja muzejske stručnjake i institucije iz više od 20 zemalja. Osnovana je 2006. godine kao regionalni program muzejske saradnje, a formalno registrovana kao udruženje 2015. godine. Od 11 muzeja osnivača prerasla je u mrežu sa više od 150 muzeja članova i 300 stručnjaka za nasleđe. BMN promoviše saradnju, razmenu znanja i profesionalni razvoj, uz istovremeno slavljenje, očuvanje i predstavljanje bogatog i raznovrsnog kulturnog nasleđa Balkana.',
                'U okviru projekta RE-MIND, BMN vodi Radni paket 5 (RP5): Primena i validacija modela izgradnje kapaciteta Mindful muzeja i doprinosi svim drugim radnim paketima. BMN koordinira organizaciju RE-MIND prezentacionih događaja, priznavanje RE-MIND ambasadora i sistem potvrđivanja statusa Mindful muzeja, validaciju modela Mindful muzeja te završno unapređenje obrazovnog i promotivnog okvira. Kroz svoju široku muzejsku mrežu, BMN podržava vidljivost, prihvatanje i dugoročnu održivost projekta.',
                'BMN je vodeća regionalna platforma za unapređenje muzejske prakse kroz izgradnju kapaciteta, umrežavanje i zajedničke projekte. Od 2010. godine podržala je više od 100 muzejskih inicijativa i trenutno upravlja Fondom Headley za kulturno nasleđe Jugoistočne Evrope, ulažući u zaštitu nasleđa širom regiona. BMN promoviše pristupačnost i inkluziju putem onlajn baze pristupačnih muzejskih usluga, objavila je 28 stručnih publikacija, organizovala 12 međunarodnih putujućih muzejskih konferencija i ustanovila prestižne nagrade za izvrsnost u muzejskoj praksi i promociji kulturnog nasleđa.',
                'BMN ima bogato iskustvo u evropskim projektima saradnje usmerenim na pristupačnost, inkluziju i profesionalni razvoj u sektoru kulturnog nasleđa. Kroz Balkansku grupu za pristupačnost muzeja (BMAG), podržava muzeje da postanu pristupačniji i inkluzivniji. BMN je učestvovala u Erazmus+ projektima Tomimeus i iNCLUSION, kao i u projektu SHIFT programa Horizont, doprinoseći stručnošću u izgradnji kapaciteta, umrežavanju i angažovanju publike.',
            ],
        ],
        'cwep' => [
            'name' => 'CWEP',
            'bio' => [
                'Centrum Wspierania Edukacji i Przedsiębiorczości (CWEP) je nevladina organizacija osnovana 2004. godine sa sedištem u Žešovu, Poljska. CWEP je posvećen promovisanju inovativnog obrazovanja, preduzetništva, naučnih istraživanja i održivog razvoja. Organizacija podstiče celoživotno učenje, socijalnu inkluziju i inovacije stvaranjem pristupačnih obrazovnih mogućnosti za ljude svih uzrasta. Kroz svoj rad, CWEP osnažuje pojedince i zajednice znanjima i veštinama potrebnim za prihvatanje digitalne transformacije, unapređenje zapošljivosti, podršku odgovornom preduzetništvu i doprinos održivijem i inkluzivnijem društvu.',
                'U okviru projekta RE-MIND, CWEP vodi Radni paket 4 (RP4): Obrazovanje i međugeneracijsko angažovanje publike u Mindful muzej iskustvima. Organizacija je odgovorna za razvoj Smernica za angažovanje publike, osmišljavanje obrazovnih sesija prilagođenih različitim generacijama i koordinaciju međugeneracijskih krugova učenja. U saradnji sa svim projektnim partnerima, CWEP doprinosi jačanju digitalnog blagostanja, mindfulness pristupa i socijalne inkluzije stvaranjem zanimljivih iskustava učenja koja podržavaju primenu RE-MIND modela Mindful muzeja.',
                'CWEP ima bogato iskustvo u razvoju obrazovnih programa, sprovođenju obuka i realizaciji evropskih projekata usmerenih na digitalne veštine, preduzetništvo, socijalnu inkluziju i održivost. Organizacija objedinjuje stručnost u istraživanju, razvoju nastavnih programa, izdavaštvu i komunikaciji radi izrade inovativnih resursa za učenje namenjenih različitim ciljnim grupama. Kroz brojne nacionalne i međunarodne inicijative, CWEP se pozicionirao kao pouzdan partner u promovisanju celoživotnog učenja, digitalnih inovacija i inkluzivnog obrazovanja, uz podršku razvoju veština potrebnih za budućnost.',
                'CWEP je učestvovao u brojnim projektima finansiranim sredstvima EU koji se bave digitalnim obrazovanjem, inkluzijom i celoživotnim učenjem. Njegovo novije iskustvo uključuje projekte MYCo, DIST-SEED, Mindfulness for Integration i SOURCE, usmerene na međugeneracijsku saradnju, digitalno pripovedanje, obrazovanje zasnovano na mindfulness pristupu i inovativne nastavne metodologije. Ovi projekti potvrđuju snažnu stručnost CWEP-a u razvoju obrazovnih resursa, programa izgradnje kapaciteta i inkluzivnih pristupa učenju.',
            ],
        ],
        'koda' => [
            'name' => 'Koda',
            'bio' => [
                'Koda je organizacija civilnog društva sa sedištem u Ljubljani, Slovenija, specijalizovana za digitalnu kulturu, etičku upotrebu tehnologije i inkluzivno digitalno angažovanje. Putem virtuelnih izložbi, digitalnih kampanja i hibridnih kulturnih iskustava, Koda promoviše celoživotno učenje i osnažuje pojedince da se u digitalnom svetu snalaze samouvereno, kreativno i kritički. Organizacija deluje na preseku kulture, obrazovanja i tehnologije, podstičući odgovorno digitalno učešće i podržavajući inovacije koje su pristupačne, etične i društveno inkluzivne.',
                'U okviru projekta RE-MIND, Koda vodi aktivnosti osiguranja kvaliteta, etike i evaluacije, obezbeđujući da realizacija projekta ostane usklađena sa standardima kvaliteta, etičkim principima i projektnim ciljevima. Organizacija razvija Okvir za osiguranje kvaliteta, etiku i evaluaciju, a istovremeno doprinosi razvoju RE-MIND kompleta alata za obuku, obrazovnih resursa i aktivnosti učenja. Zahvaljujući stručnosti u oblasti digitalnog blagostanja i odgovornih inovacija, Koda podržava ostvarivanje visokokvalitetnih i inkluzivnih projektnih rezultata.',
                'Koda poseduje veliko znanje u oblastima digitalne kulture, etičke tehnologije, digitalnog blagostanja i inkluzivnog onlajn učešća. Organizacija razvija inovativne obrazovne resurse, digitalne kampanje i participativne kulturne inicijative koje promovišu odgovornu upotrebu tehnologije i digitalnu inkluziju. Zahvaljujući snažnom iskustvu u upravljanju projektima, kreativnoj komunikaciji i međusektorskoj saradnji, Koda podržava celoživotno učenje i osnažuje pojedince i organizacije da se samouvereno i etično angažuju u digitalnim okruženjima, uz podsticanje pristupačnih i društveno odgovornih inovacija.',
                'Koda ima veliko iskustvo u digitalnom obrazovanju, radu sa mladima i izgradnji kapaciteta, sa snažnim fokusom na digitalnu pismenost, bezbednost na internetu, odgovornu upotrebu tehnologije i digitalno blagostanje. Kroz nacionalne i međunarodne projekte razvijala je obrazovne resurse, sprovodila obuke za mlade i stručnjake i realizovala inicijative koje promovišu bezbedno, inkluzivno i etično digitalno učešće u različitim zajednicama.',
            ],
        ],
        'mov' => [
            'name' => 'Muzej Vojvodine (MoV)',
            'bio' => [
                'Muzej Vojvodine je jedna od vodećih kulturnih institucija u Srbiji, sa sedištem u Novom Sadu, čiji počeci sežu do Srpske narodne zbirke osnovane u Budimpešti 1847. godine. Posvećen očuvanju i tumačenju bogatog kulturnog nasleđa Vojvodine, Muzej kroz svoje obimne zbirke i izložbe dokumentuje više od 8.000 godina ljudske istorije. Usmeren na potrebe savremene publike, Muzej promoviše obrazovanje, inkluziju i celoživotno učenje, podstičući posetioce da bolje razumeju prošlost i aktivno se uključe u sadašnjost i budućnost.',
                'U okviru projekta RE-MIND, Muzej Vojvodine učestvuje kao savetodavni i pilot-partner u svim projektnim aktivnostima. Muzej ima ključnu ulogu u Radnim paketima 4 i 5, podržavajući aktivnosti angažovanja publike, kao i primenu i validaciju modela izgradnje kapaciteta Mindful muzeja. Kroz svoju obrazovnu stručnost i neposrednu interakciju sa različitim grupama posetilaca, Muzej doprinosi testiranju i unapređenju inovativnih pristupa mindful, inkluzivnim i međugeneracijskim muzejskim iskustvima.',
                'Muzej Vojvodine objedinjuje bogatu stručnost u arheologiji, etnologiji, istoriji i likovnoj umetnosti sa snažnom posvećenošću muzejskom obrazovanju i angažovanju publike. Njegov multidisciplinarni tim kustosa, konzervatora, istraživača i muzejskih pedagoga razvija inovativne izložbe i obrazovne programe za posetioce svih uzrasta. Aktivnim učešćem u istraživačkim projektima, međunarodnim konferencijama i profesionalnim mrežama, Muzej doprinosi unapređenju muzejske prakse i promoviše kulturno nasleđe kroz inkluzivna i podsticajna iskustva učenja.',
                'Muzej Vojvodine ima veliko iskustvo u međunarodnoj saradnji kroz zajedničke izložbe, istraživačke inicijative, programe kulturne razmene i partnerstva sa muzejima i institucijama kulturnog nasleđa širom Evrope. Ove saradnje ojačale su njegovu stručnost u angažovanju publike, tumačenju nasleđa i realizaciji projekata, potvrđujući njegovu ulogu aktivnog učesnika u međunarodnom kulturnom dijalogu i inovacijama u muzejskoj praksi.',
            ],
        ],
        'nimb' => [
            'name' => 'Nacionalna ustanova Zavod i muzej Bitolj (NIMB)',
            'bio' => [
                'Nacionalna ustanova Zavod i muzej Bitolj (NIMB) jedna je od vodećih institucija kulturnog nasleđa u Severnoj Makedoniji, koja objedinjuje zaštitu, istraživanje i predstavljanje materijalnog i nematerijalnog kulturnog nasleđa. Sa sedištem u Bitolju, ustanova zapošljava multidisciplinarni tim arheologa, etnologa, istoričara, istoričara umetnosti, konzervatora i muzejskih stručnjaka. Uz podršku Ministarstva kulture Severne Makedonije, NIMB svake godine realizuje više od 50 nacionalnih i međunarodnih projekata, promovišući očuvanje nasleđa, muzejsko obrazovanje, pristupačnost i angažovanje različitih grupa javnosti.',
                'U okviru projekta RE-MIND, NIMB učestvuje kao demonstracioni i pilot-partner, doprinoseći primeni i validaciji modela Mindful muzeja. Ustanova učestvuje u svim projektnim aktivnostima, podržava razvoj obrazovnih resursa, stručne obuke i interaktivne inicijative angažovanja publike. Pilotiranjem pristupa zasnovanih na mindfulness principima u muzejskom okruženju, NIMB pomaže u proceni delotvornosti modela u podsticanju digitalnog blagostanja, međugeneracijskog dijaloga i društveno odgovornog muzejskog iskustva.',
                'Sa više od 90 godina neprekidnog rada, NIMB poseduje veliko iskustvo u muzejskom obrazovanju, pristupačnosti, tumačenju kulturnog nasleđa i međunarodnom upravljanju projektima. Ustanova ima više od dve decenije iskustva u obrazovnim programima i više od deset godina posvećenog rada na unapređenju pristupačnosti za različite grupe publike. Kroz inkluzivne izložbe, inovativne obrazovne inicijative i snažna partnerstva, NIMB promoviše ravnopravan pristup kulturnom nasleđu, istovremeno unapređujući savremenu muzejsku praksu i angažovanje zajednice.',
                'NIMB godišnje realizuje više od 50 projekata u oblastima zaštite nasleđa, muzejskog tumačenja, obrazovanja i pristupačnosti. Ustanova upravlja značajnim lokalitetima kulturnog nasleđa, uključujući Heraclea Lyncestis, predvodila je inicijative pristupačnosti, razvila taktilne izložbe predstavljene u inostranstvu i ostvarila široku saradnju sa evropskim partnerima. Kao aktivan član međunarodnih muzejskih mreža, NIMB primenjuje evropske standarde u očuvanju nasleđa, inkluziji i održivom kulturnom turizmu.',
            ],
        ],
        'spac' => [
            'name' => 'SPAC — Scuola nazionale del patrimonio e delle attività culturali',
            'bio' => [
                'Scuola nazionale del patrimonio e delle attività culturali (Scuola) je italijanska ustanova sa sedištem u Rimu, koju je Ministarstvo kulture osnovalo 2015. godine radi podsticanja kontinuiranog profesionalnog razvoja stručnjaka za kulturno nasleđe. Kao međunarodni centar za obuku, istraživanje i inovacije, Scuola podržava transformaciju kulturnog sektora kroz interdisciplinarno učenje, primenjena istraživanja i međunarodnu saradnju. Njen rad je usmeren na upravljanje nasleđem, digitalnu transformaciju, pristupačnost i inkluziju, podstičući razmenu znanja i jačanje profesionalnih kapaciteta u celokupnom ekosistemu kulturnog nasleđa.',
                'U okviru projekta RE-MIND, Scuola učestvuje kao demonstracioni i pilot-partner, doprinoseći zajedničkom kreiranju, primeni, testiranju i validaciji modela izgradnje kapaciteta Mindful muzeja. Organizacija je aktivno uključena u operativne radne pakete projekta, podržavajući programe obuke, radionice i aktivnosti validacije. Scuola takođe doprinosi diseminaciji i angažovanju zainteresovanih strana putem svojih širokih nacionalnih i međunarodnih mreža i koordinira organizaciju RE-MIND prezentacionog događaja u Italiji.',
                'Scuola ima veliko iskustvo u osmišljavanju i realizaciji programa stručnog usavršavanja za stručnjake iz muzeja, arhiva, biblioteka i oblasti kulturnog nasleđa. Razvija inovativne mogućnosti učenja u neposrednom, onlajn i kombinovanom formatu, podržavajući rukovodioce muzeja, javne službenike, donosioce odluka i stručnjake za nasleđe. Bliskom saradnjom sa italijanskim Ministarstvom kulture i međunarodnim organizacijama, Scuola je izgradila snažnu stručnost u upravljanju nasleđem, digitalnoj transformaciji, pristupačnosti, međunarodnoj saradnji i celoživotnom učenju, pomažući jačanju kulturnog sektora kroz razmenu znanja i izgradnju kapaciteta.',
                'Scuola je učestvovala u brojnim evropskim i međunarodnim inicijativama usmerenim na razvoj veština i inovacije u oblasti kulturnog nasleđa, uključujući projekat CHARTER Erasmus+ Blueprint, saradnje u okviru programa Horizont Evropa i Dicolab, italijanski nacionalni program digitalnih veština u kulturnom sektoru. Takođe realizuje međunarodne programe izgradnje kapaciteta za stručnjake za nasleđe i upravlja platformom za digitalno učenje sa više od 34.000 korisnika.',
            ],
        ],
        'tmnt' => [
            'name' => 'Tehnički muzej Nikola Tesla (TMNT)',
            'bio' => [
                'Tehnički muzej Nikola Tesla (TMNT) nalazi se u Zagrebu, Hrvatska, i osnovan je 1954. godine kao vodeći muzej u zemlji posvećen nauci, tehnologiji i industrijskom nasleđu. Smešten u značajnom arhitektonskom kompleksu koji je projektovao ugledni hrvatski arhitekta Marijan Haberle, muzej čuva i predstavlja naučno i tehnološko nasleđe Hrvatske kroz inovativne izložbe i obrazovne programe. Kao jedan od najposećenijih muzeja u zemlji, TMNT aktivno promoviše celoživotno učenje, angažovanje javnosti i interdisciplinarnu saradnju, stvarajući interaktivna iskustva koja povezuju nauku, kulturu i društvo.',
                'U okviru projekta RE-MIND, TMNT učestvuje kao savetodavni i pilot-partner i doprinosi svim projektnim aktivnostima. Muzej ima aktivnu ulogu u inicijativama za angažovanje publike i podržava primenu i validaciju modela izgradnje kapaciteta Mindful muzeja u okviru radnih paketa 4 i 5. Testiranjem inovativnih obrazovnih pristupa i uključivanjem različitih grupa posetilaca, TMNT doprinosi razvoju mindful, inkluzivnih i digitalno uravnoteženih muzejskih iskustava.',
                'TMNT čuva zbirku sa više od 11.000 predmeta kulturnog nasleđa i ima dugogodišnje iskustvo u muzejskom obrazovanju, angažovanju javnosti i naučnoj komunikaciji. Muzej razvija inovativne obrazovne programe u partnerstvu sa univerzitetima, naučnim centrima, nevladinim organizacijama i stručnjacima iz oblasti nauke, umetnosti i humanističkih nauka. Kao suorganizator Festivala nauke u Hrvatskoj, TMNT je prepoznat po promovisanju interdisciplinarnog učenja, povezivanju nauke i kulture i razvoju muzejskih iskustava usmerenih ka budućnosti koja odgovaraju na promenljive društvene potrebe.',
                'TMNT je realizovao brojne nacionalne i međunarodne projekte koji promovišu socijalnu inkluziju, angažovanje javnosti, rodnu ravnopravnost i učešće manjinskih grupa. Muzej aktivno podržava interdisciplinarne pristupe tumačenju nasleđa i sarađuje sa evropskim partnerima kroz međunarodne mreže i inicijative finansirane sredstvima EU, doprinoseći inovacijama u muzejskom obrazovanju, pristupačnosti i razvoju publike.',
            ],
        ],
        'brainster' => [
            'name' => 'Brainster',
            'bio' => [
                'Brainster je vodeća organizacija u oblasti obrazovnih tehnologija sa sedištem u Skoplju, Severna Makedonija, osnovana 2015. godine. Kroz praktično obrazovanje usmereno na potrebe industrije, Brainster osnažuje pojedince veštinama potrebnim za budućnost u oblastima informacionih tehnologija, veštačke inteligencije, digitalnog marketinga, dizajna i preduzetništva. Organizacija je obrazovala više od 14.000 polaznika i razvila inovativna digitalna rešenja za učenje, uključujući sopstveni sistem za upravljanje učenjem i platformu za učenje zasnovanu na veštačkoj inteligenciji.',
                'U projektu RE-MIND, Brainster vodi Radni paket 6 (Work Package 6 on Communication, Dissemination and Sustainability) posvećen komunikaciji, diseminaciji i održivosti, nadgledajući komunikacionu strategiju projekta, vizuelni identitet, internet stranicu, društvene mreže i angažovanje zainteresovanih strana. Brainster takođe doprinosi razvoju Pametnog ekosistema učenja podržavajući okvir za mikrokvalifikacije i institucionalno priznavanje. Zahvaljujući bogatom iskustvu u digitalnom obrazovanju, tehnologijama učenja, komunikacionim kampanjama i evropskim projektima saradnje, Brainster obezbeđuje široku vidljivost, dugoročnu održivost i smislen uticaj rezultata projekta širom Evrope.',
            ],
        ],
    ],
];
