<?php

return [
    'eyebrow' => 'Ljudje za RE-MIND',
    'title' => 'KONZORCIJ',
    'contact_label' => 'Kontakt',
    'back_to_consortium' => 'Nazaj na Konzorcij',
    'intro_title' => 'MOČNO EVROPSKO PARTNERSTVO',
    'intro_paragraph' => 'RE-MIND združuje 11 partnerskih organizacij iz 7 evropskih držav, ki jih povezuje skupna zavezanost ustvarjanju bolj čuječih, vključujočih in angažiranih muzejskih izkušenj. Partnerji iz Srbije, Italije, Hrvaške, Poljske, Slovenije, Bosne in Hercegovine ter Severne Makedonije s čezmejnim sodelovanjem prispevajo svoje strokovno znanje, izkušnje in kulturne perspektive za spodbujanje inovacij in trajnega vpliva v evropskem muzejskem sektorju.',

    'partners' => [
        'mei' => [
            'name' => 'MEI – Minds Europe – Institute for Research Excellence and Technological Advancement',
            'bio' => [
                'Minds Europe – Institute for Research Excellence and Technological Advancement (MEI) je nevladna, neprofitna raziskovalno-razvojna organizacija s sedežem v Novem Sadu v Srbiji, ustanovljena leta 2020. MEI svoje delovanje gradi na štirih strateških stebrih– Mind-set CULTURE, NATURE, PEOPLE in AI – ter povezuje akademsko odličnost s praktičnimi družbenimi inovacijami. Organizacija deluje na presečišču kulture, izobraževanja, digitalne preobrazbe, dobrega počutja in vključujočega sodelovanja skupnosti ter razvija raziskovalno utemeljene metodologije, izobraževalne programe in inovativne rešitve, ki podpirajo trajnostni družbeni razvoj in krepijo zmogljivosti kulturnih ter izobraževalnih ustanov.',
                'Kot koordinator projekta RE-MIND MEI vodi delovni sklop 1: Upravljanje in koordinacija projekta ter skrbi za učinkovito izvajanje, finančno upravljanje, zagotavljanje kakovosti in splošno strateško usmeritev projekta. MEI vodi tudi pripravo načrta Čuječega muzeja v okviru delovnega sklopa 2 ter sodeluje pri oblikovanju programa usposabljanja, izobraževalnih virov, medgeneracijskih delavnic, predstavitvenih dogodkov in kulturnih krožkov. Organizacija ima osrednjo vlogo pri prenosu raziskovalnih ugotovitev v praktična orodja za muzeje po vsej Evropi.',
                'MEI združuje strokovno znanje s področij čuječnosti, digitalnega dobrega počutja, umirjene tehnologije, kulturne udeležbe, izobraževanja, IKT in interakcije človek-računalnik. Organizacija razvija na dokazih temelječe metodologije, ki znanstvene raziskave pretvarjajo v praktične rešitve za kulturna in izobraževalna okolja. Z obsežnimi izkušnjami na področju interdisciplinarnih raziskav, krepitve zmogljivosti, digitalnega učenja in inovacij MEI pomaga organizacijam ustvarjati vključujoča, privlačna in digitalno uravnotežena okolja ter hkrati spodbuja dobro počutje in vseživljenjsko učenje.',
                'MEI je koordiniral in sodeloval pri številnih evropskih projektih, financiranih iz programov Ustvarjalna Evropa, Obzorje Evropa, Erasmus+ in IPA. Njegove izkušnje vključujejo krepitev zmogljivosti, digitalno izobraževanje, kulturno udeležbo, sodelovanje deležnikov, ocenjevanje učinkov in inovacije. Organizacija je sodelovala tudi pri pomembnih mednarodnih ocenjevalnih pobudah, med drugim pri Expo 2020 Dubai in projektu Novi Sad – Evropska prestolnica kulture.',
            ],
        ],
        'algebra' => [
            'name' => 'Algebra Bernays University',
            'bio' => [
                'Algebra Bernays University je ena vodilnih zasebnih visokošolskih ustanov na Hrvaškem in del največje zasebne izobraževalne organizacije v državi in regiji, ki od ustanovitve leta 1998 deluje v več kot 20 mestih. Univerza si prizadeva ustvarjati inovativno učno okolje, ki študente, raziskovalce in strokovnjake opolnomoča, da postanejo vodilni pri razvoju in uporabi digitalnih tehnologij. Njena vizija je izobraževati etične inovatorje in prihodnje nosilce sprememb, ki prispevajo k tehnološkemu napredku in trajnostnemu družbenemu razvoju.',
                'V projektu RE-MIND Algebra Bernays University vodi delovni sklop 3: Vzpostavitev pametnega učnega ekosistema RE-MIND za mikrodokazila in institucionalno potrditev. Univerza je odgovorna za načrtovanje in razvoj digitalne učne platforme projekta, podporo pri vključevanju gradiv za usposabljanje v interaktivno spletno okolje ter sodelovanje pri razvoju okvira za mikrodokazila. Sodeluje tudi pri izvajanju projekta, dejavnostih potrjevanja in razširjanju rezultatov.',
                'Algebra Bernays University je prepoznavna po multidisciplinarnem, na študente osredotočenem pristopu k izobraževanju ter po močnem strokovnem znanju na področju digitalnega učenja, načrtovanja poučevanja in STEM. Univerza razvija inovativne izobraževalne programe in vključuje napredne metode poučevanja, med drugim poslovne simulacije in interaktivne učne tehnologije. S tesnim sodelovanjem z industrijskimi partnerji in obsežnimi izkušnjami pri projektih digitalne preobrazbe zagotavlja strokovno znanje za razvoj visokokakovostnih učnih okolij ter podporo inovacijam v izobraževanju in strokovnem usposabljanju.',
                'Algebra Bernays University ima obsežne izkušnje z razvojem in izvajanjem digitalnega izobraževanja ter rešitev e-učenja za organizacije javnega in zasebnega sektorja. Uspešno je izvedla projekte na področjih načrtovanja poučevanja, digitalne preobrazbe, mikrodokazil in vseživljenjskega učenja ter pri tem povezala znanje s področij STEM, izobraževalnih tehnologij in inovativnih učnih metodologij za podporo strokovnemu razvoju v različnih sektorjih.',
            ],
        ],
        'adm' => [
            'name' => 'Archivio della Memoria (AdM)',
            'bio' => [
                'Archivio della Memoria (AdM) je italijanska neprofitna kulturna organizacija, ustanovljena leta 2002 s sedežem v Rimu. Specializirana je za ohranjanje in promocijo kulturne dediščine z uporabo digitalnih tehnologij, ustne zgodovine, avdiovizualnega pripovedovanja in participativnih izobraževalnih pristopov. Od leta 2006 sodeluje z Univerzo v Rimu Tor Vergata in je del mreže Tor Vergata Science Park. Z raziskavami, usposabljanji in dejavnostmi ozaveščanja AdM sodeluje s šolami, univerzami, kulturnimi ustanovami in lokalnimi skupnostmi ter spodbuja vseživljenjsko učenje, socialno vključevanje, dobro počutje in dejavno kulturno udeležbo.',
                'V projektu RE-MIND Archivio della Memoria vodi delovni sklop 2: Razvoj modela izobraževanja in doseganja občinstev Čuječega muzeja ter kompleta orodij za usposabljanje. Organizacija usklajuje prepoznavanje dobrih praks, razvija komplet orodij RE-MIND in večpredstavnostne učne vire ter sodeluje pri dejavnostih krepitve zmogljivosti muzejskih strokovnjakov. AdM podpira tudi izobraževalna srečanja, medgeneracijske delavnice in dejavnosti razširjanja ter pomaga spodbujati čuječe, vključujoče in digitalno uravnotežene muzejske izkušnje.',
                'Archivio della Memoria ima obsežno strokovno znanje s področij kulturne dediščine, digitalnega pripovedovanja, avdiovizualne produkcije, participativnega raziskovanja in izobraževalnih inovacij. V zadnjih dveh desetletjih je organizacija ustvarila približno 2.000 kakovostnih videointervjujev, pri čemer je ustno zgodovino povezala z metodologijami družbenega pripovedovanja. Njena multidisciplinarna ekipa ima bogate izkušnje z razvojem programov usposabljanja, večpredstavnostnih izobraževalnih virov in kampanj ozaveščanja o digitalnih inovacijah, dobrem počutju, socialnem vključevanju in medgeneracijskem učenju v okviru nacionalnih in evropskih pobud.',
                'Archivio della Memoria je sodeloval pri številnih evropskih projektih na področju izobraževanja odraslih, poklicnega izobraževanja in usposabljanja, mladine, šolstva in kulturne dediščine. Med njegovimi izkušnjami so projekti CHART, DIST-SEED, Erasmediah, DataPro, ACCESS, DEED in SIATE, ki se osredotočajo na kulturno dediščino, digitalno ozaveščenost, duševno dobro počutje, okoljsko trajnost, socialno vključevanje in krepitev zmogljivosti z inovativnimi izobraževalnimi metodologijami.',
            ],
        ],
        'bmn' => [
            'name' => 'Balkan Museum Network',
            'bio' => [
                'Balkan Museum Network (BMN) je mednarodna mreža s sedežem v Sarajevu v Bosni in Hercegovini, ki povezuje muzejske strokovnjake in ustanove iz več kot 20 držav. Leta 2006 je bila vzpostavljena kot regionalni program muzejskega sodelovanja, leta 2015 pa formalno registrirana kot združenje. Iz 11 ustanovnih muzejev je zrasla v mrežo več kot 150 muzejev članov in 300 strokovnjakov za dediščino. BMN spodbuja sodelovanje, izmenjavo znanja in strokovni razvoj ter hkrati slavi, ohranja in predstavlja bogato in raznoliko kulturno dediščino Balkana.',
                'V projektu RE-MIND BMN vodi delovni sklop 5: Izvedba in potrditev modela krepitve zmogljivosti Čuječega muzeja ter sodeluje pri vseh drugih delovnih sklopih. BMN usklajuje organizacijo predstavitvenih dogodkov RE-MIND, imenovanje ambasadorjev RE-MIND in sistem priznanja Čuječi muzej, potrjevanje modela Čuječega muzeja ter končno izpopolnitev izobraževalnega okvira in okvira za vključevanje občinstva. S svojo obsežno muzejsko mrežo podpira prepoznavnost, sprejetje in dolgoročno trajnost projekta.',
                'BMN je vodilna regionalna platforma za krepitev muzejske prakse z razvojem zmogljivosti, mreženjem in sodelovalnimi projekti. Od leta 2010 je podprla več kot 100 muzejskih pobud, trenutno pa upravlja sklad Headley Southeast Europe Cultural Heritage Fund, ki vlaga v varovanje dediščine po vsej regiji. BMN spodbuja dostopnost in vključevanje tudi s spletno zbirko dostopnih muzejskih storitev, izdala je 28 strokovnih publikacij, organizirala 12 mednarodnih potujočih muzejskih konferenc ter ustanovila ugledne nagrade za odličnost v muzejski praksi in promociji kulturne dediščine.',
                'BMN ima obsežne izkušnje z evropskimi projekti sodelovanja, osredotočenimi na dostopnost, vključevanje in strokovni razvoj v sektorju kulturne dediščine. Prek skupine Balkan Museum Access Group (BMAG) podpira muzeje pri izboljševanju dostopnosti in vključujočnosti. BMN je sodelovala pri projektih Erasmus+, kot sta Tomimeus in iNCLUSION, ter pri projektu Obzorje SHIFT, pri čemer je prispevala strokovno znanje s področij krepitve zmogljivosti, mreženja in vključevanja občinstva.',
            ],
        ],
        'cwep' => [
            'name' => 'CWEP',
            'bio' => [
                'Centrum Wspierania Edukacji i Przedsiębiorczości (CWEP) je nevladna organizacija, ustanovljena leta 2004 s sedežem v Rzeszówu na Poljskem. CWEP je namenjena spodbujanju inovativnega izobraževanja, podjetništva, znanstvenih raziskav in trajnostnega razvoja. Organizacija spodbuja vseživljenjsko učenje, socialno vključevanje in inovacije z ustvarjanjem dostopnih izobraževalnih priložnosti za ljudi vseh starosti. S svojim delom posameznike in skupnosti opolnomoča z znanjem in spretnostmi, potrebnimi za prilagajanje digitalni preobrazbi, krepitev zaposljivosti, podporo odgovornemu podjetništvu ter prispevanje k bolj trajnostni in vključujoči družbi.',
                'V projektu RE-MIND CWEP vodi delovni sklop 4: Izobraževanje in medgeneracijsko vključevanje občinstva v izkušnje Čuječega muzeja. Organizacija je odgovorna za razvoj smernic za vključevanje občinstva, oblikovanje izobraževalnih srečanj, prilagojenih različnim generacijam, ter koordinacijo medgeneracijskih učnih krožkov. V sodelovanju z vsemi projektnimi partnerji CWEP krepi digitalno dobro počutje, čuječnost in socialno vključenost z ustvarjanjem privlačnih učnih izkušenj, ki podpirajo uvedbo modela Čuječega muzeja RE-MIND.',
                'CWEP ima obsežne izkušnje z razvojem izobraževalnih programov, izvajanjem usposabljanj in evropskih projektov, osredotočenih na digitalne spretnosti, podjetništvo, socialno vključevanje in trajnost. Organizacija združuje strokovno znanje s področij raziskovanja, razvoja učnih načrtov, založništva in komuniciranja ter ustvarja inovativne učne vire za različne ciljne skupine. Z mnogimi nacionalnimi in mednarodnimi pobudami se je uveljavila kot zaupanja vreden partner pri spodbujanju vseživljenjskega učenja, digitalnih inovacij in vključujočega izobraževanja ter pri razvoju spretnosti za prihodnost.',
                'CWEP je sodelovala pri številnih projektih, financiranih iz sredstev EU, na področjih digitalnega izobraževanja, vključevanja in vseživljenjskega učenja. Med novejšimi so MYCo, DIST-SEED, Mindfulness for Integration in SOURCE, ki se osredotočajo na medgeneracijsko sodelovanje, digitalno pripovedovanje, izobraževanje na podlagi čuječnosti in inovativne učne metodologije. Ti projekti potrjujejo močno strokovno znanje CWEP pri razvoju izobraževalnih virov, programov krepitve zmogljivosti in vključujočih učnih pristopov.',
            ],
        ],
        'koda' => [
            'name' => 'Koda',
            'bio' => [
                'Koda je organizacija civilne družbe s sedežem v Ljubljani v Sloveniji, specializirana za digitalno kulturo, etično uporabo tehnologije in vključujoče digitalno sodelovanje. Z virtualnimi razstavami, digitalnimi kampanjami in hibridnimi kulturnimi izkušnjami Koda spodbuja vseživljenjsko učenje ter posameznike opolnomoča za samozavestno, ustvarjalno in kritično delovanje v digitalnem svetu. Organizacija deluje na presečišču kulture, izobraževanja in tehnologije, spodbuja odgovorno digitalno udeležbo ter podpira dostopne, etične in družbeno vključujoče inovacije.',
                'V projektu RE-MIND Koda vodi dejavnosti zagotavljanja kakovosti, etike in vrednotenja ter skrbi, da izvajanje projekta ostaja usklajeno s standardi kakovosti, etičnimi načeli in projektnimi cilji. Organizacija razvija okvir za zagotavljanje kakovosti, etiko in vrednotenje, hkrati pa sodeluje pri razvoju kompleta orodij za usposabljanje RE-MIND, izobraževalnih virov in učnih dejavnosti. S svojim strokovnim znanjem na področju digitalnega dobrega počutja in odgovornih inovacij Koda podpira pripravo visokokakovostnih in vključujočih projektnih rezultatov.',
                'Koda ima obsežno strokovno znanje s področij digitalne kulture, etične tehnologije, digitalnega dobrega počutja in vključujoče spletne udeležbe. Razvija inovativne izobraževalne vire, digitalne kampanje in participativne kulturne pobude, ki spodbujajo odgovorno uporabo tehnologije in digitalno vključevanje. Z bogatimi izkušnjami pri vodenju projektov, kreativnem komuniciranju in medsektorskem sodelovanju podpira vseživljenjsko učenje ter posameznike in organizacije opolnomoča za samozavestno in etično delovanje v digitalnih okoljih, hkrati pa spodbuja dostopne in družbeno odgovorne inovacije.',
                'Koda ima obsežne izkušnje na področjih digitalnega izobraževanja, mladinskega dela in krepitve zmogljivosti, s posebnim poudarkom na digitalni pismenosti, spletni varnosti, odgovorni uporabi tehnologije in digitalnem dobrem počutju. V nacionalnih in mednarodnih projektih je razvila izobraževalne vire, izvajala usposabljanja za mlade in strokovnjake ter uvedla pobude, ki spodbujajo varno, vključujočo in etično digitalno udeležbo v raznolikih skupnostih.',
            ],
        ],
        'mov' => [
            'name' => 'Muzej Vojvodine (MoV)',
            'bio' => [
                'Muzej Vojvodine je eden vodilnih kulturnih ustanov v Srbiji. Nahaja se v Novem Sadu, njegovi začetki pa segajo do Srbske narodne zbirke, ustanovljene leta 1847 v Budimpešti. Muzej je posvečen ohranjanju in interpretaciji bogate kulturne dediščine Vojvodine ter z obsežnimi zbirkami in razstavami dokumentira več kot 8.000 let človeške zgodovine. Zavezan je sodobnim občinstvom, zato spodbuja izobraževanje, vključevanje in vseživljenjsko učenje ter obiskovalce spodbuja k boljšemu razumevanju preteklosti in dejavnemu odnosu do sedanjosti in prihodnosti.',
                'V projektu RE-MIND Muzej Vojvodine sodeluje kot svetovalni in pilotni partner ter je vključen v vse projektne dejavnosti. Ključno vlogo ima v delovnih sklopih 4 in 5, kjer podpira dejavnosti vključevanja občinstva ter izvajanje in potrjevanje modela krepitve zmogljivosti Čuječega muzeja. S svojim pedagoškim strokovnim znanjem in tesnim stikom z različnimi skupinami obiskovalcev prispeva k preizkušanju in izpopolnjevanju inovativnih pristopov k čuječim, vključujočim in medgeneracijskim muzejskim izkušnjam.',
                'Muzej Vojvodine združuje obsežno strokovno znanje s področij arheologije, etnologije, zgodovine in likovne umetnosti z močno zavezanostjo muzejski pedagogiki in vključevanju občinstva. Njegova multidisciplinarna ekipa kustosov, konservatorjev, raziskovalcev in muzejskih pedagogov razvija inovativne razstave in izobraževalne programe za obiskovalce vseh starosti. Z dejavnim sodelovanjem v raziskovalnih projektih, na mednarodnih konferencah in v strokovnih mrežah muzej prispeva k razvoju muzejske prakse ter kulturno dediščino približuje z vključujočimi in privlačnimi učnimi izkušnjami.',
                'Muzej Vojvodine ima obsežne izkušnje z mednarodnim sodelovanjem v okviru skupnih razstav, raziskovalnih pobud, programov kulturne izmenjave ter partnerstev z muzeji in ustanovami za dediščino po vsej Evropi. Ta sodelovanja so okrepila njegovo strokovno znanje na področjih vključevanja občinstva, interpretacije dediščine in izvajanja projektov ter utrdila njegovo vlogo dejavnega soustvarjalca mednarodnega kulturnega dialoga in inovacij v muzejski praksi.',
            ],
        ],
        'nimb' => [
            'name' => 'Nacionalna ustanova Zavod in muzej Bitola (NIMB)',
            'bio' => [
                'Nacionalna ustanova Zavod in muzej Bitola (NIMB) je ena vodilnih ustanov kulturne dediščine v Severni Makedoniji, ki povezuje varovanje, raziskovanje in predstavljanje snovne in nesnovne kulturne dediščine. Ustanova s sedežem v Bitoli zaposluje multidisciplinarno ekipo arheologov, etnologov, zgodovinarjev, umetnostnih zgodovinarjev, konservatorjev in muzejskih strokovnjakov. Ob podpori Ministrstva za kulturo Severne Makedonije NIMB vsako leto izvede več kot 50 nacionalnih in mednarodnih projektov ter spodbuja ohranjanje dediščine, muzejsko izobraževanje, dostopnost in vključevanje raznolikih javnosti.',
                'V projektu RE-MIND NIMB sodeluje kot predstavitveni in pilotni partner ter prispeva k izvedbi in potrjevanju modela Čuječega muzeja. Ustanova sodeluje pri vseh projektnih dejavnostih ter podpira razvoj izobraževalnih virov, strokovnih usposabljanj in interaktivnih pobud za vključevanje občinstva. S pilotnim preizkušanjem pristopov, ki temeljijo na čuječnosti, v muzejskem okolju NIMB pomaga ocenjevati učinkovitost modela pri spodbujanju digitalnega dobrega počutja, medgeneracijskega dialoga in družbeno odzivnih muzejskih izkušenj.',
                'NIMB ima več kot 90 let neprekinjenega delovanja in obsežno strokovno znanje na področjih muzejske pedagogike, dostopnosti, interpretacije kulturne dediščine in mednarodnega projektnega vodenja. Ustanova ima več kot dve desetletji izkušenj z izobraževalnimi programi in več kot deset let namenskega dela pri izboljševanju dostopnosti za različna občinstva. Z vključujočimi razstavami, inovativnimi izobraževalnimi pobudami in močnimi partnerstvi spodbuja enak dostop do kulturne dediščine ter razvoj sodobnih muzejskih praks in sodelovanja skupnosti.',
                'NIMB vsako leto izvede več kot 50 projektov s področij varovanja dediščine, muzejske interpretacije, izobraževanja in dostopnosti. Upravlja pomembna območja kulturne dediščine, med drugim Heraclea Lyncestis, vodi pobude za dostopnost, razvija tipne razstave, predstavljene tudi v tujini, ter obsežno sodeluje z evropskimi partnerji. Kot dejaven član mednarodnih muzejskih mrež uporablja evropske standarde pri ohranjanju dediščine, vključevanju in trajnostnem kulturnem turizmu.',
            ],
        ],
        'spac' => [
            'name' => 'SPAC — Scuola nazionale del patrimonio e delle attività culturali',
            'bio' => [
                'Scuola nazionale del patrimonio e delle attività culturali (SPAC) je italijanska ustanova s sedežem v Rimu, ki jo je leta 2015 ustanovilo Ministrstvo za kulturo za spodbujanje stalnega strokovnega razvoja strokovnjakov za kulturno dediščino. Kot mednarodno središče za usposabljanje, raziskovanje in inovacije SPAC podpira preobrazbo kulturnega sektorja z interdisciplinarnim učenjem, uporabnimi raziskavami in mednarodnim sodelovanjem. Njeno delo se osredotoča na upravljanje dediščine, digitalno preobrazbo, dostopnost in vključevanje ter spodbuja izmenjavo znanja in krepitev strokovnih zmogljivosti v celotnem ekosistemu kulturne dediščine.',
                'V projektu RE-MIND SPAC sodeluje kot predstavitveni in pilotni partner ter prispeva k soustvarjanju, izvajanju, preizkušanju in potrjevanju modela krepitve zmogljivosti Čuječega muzeja. Dejavna je v operativnih delovnih sklopih projekta ter podpira programe usposabljanja, delavnice in dejavnosti potrjevanja. Scuola prek svojih obsežnih nacionalnih in mednarodnih mrež prispeva tudi k razširjanju rezultatov in vključevanju deležnikov ter usklajuje organizacijo predstavitvenega dogodka RE-MIND v Italiji.',
                'SPAC ima obsežno strokovno znanje pri oblikovanju in izvajanju programov strokovnega razvoja za muzejske, arhivske, knjižnične in druge strokovnjake s področja kulturne dediščine. Razvija inovativne možnosti učenja v živo, na spletu in v kombiniranih oblikah ter podpira vodje muzejev, javne uslužbence, oblikovalce politik in strokovnjake za dediščino. V tesnem sodelovanju z italijanskim Ministrstvom za kulturo in mednarodnimi organizacijami je razvila močno strokovno znanje na področjih upravljanja dediščine, digitalne preobrazbe, dostopnosti, mednarodnega sodelovanja in vseživljenjskega učenja ter z izmenjavo znanja in krepitvijo zmogljivosti pomaga krepiti kulturni sektor.',
                'SPAC je sodelovala pri številnih evropskih in mednarodnih pobudah, osredotočenih na razvoj spretnosti in inovacije na področju kulturne dediščine, med drugim pri projektu CHARTER Erasmus+ Blueprint, sodelovanjih v okviru programa Obzorje Evropa in Dicolabu, italijanskem nacionalnem programu za digitalne spretnosti v kulturnem sektorju. Izvaja tudi mednarodne programe krepitve zmogljivosti za strokovnjake za dediščino in upravlja digitalno učno platformo z več kot 34.000 uporabniki.',
            ],
        ],
        'tmnt' => [
            'name' => 'Tehniški muzej Nikola Tesla (TMNT)',
            'bio' => [
                'Tehniški muzej Nikola Tesla (TMNT) se nahaja v Zagrebu na Hrvaškem in je bil ustanovljen leta 1954 kot vodilni državni muzej, posvečen znanosti, tehnologiji in industrijski dediščini. Domuje v znamenitem arhitekturnem kompleksu priznanega hrvaškega arhitekta Marijana Haberleja ter z inovativnimi razstavami in izobraževalnimi programi ohranja in predstavlja hrvaško znanstveno in tehnološko dediščino. Kot eden najbolj obiskanih muzejev v državi TMNT dejavno spodbuja vseživljenjsko učenje, vključevanje javnosti in interdisciplinarno sodelovanje ter ustvarja interaktivne izkušnje, ki povezujejo znanost, kulturo in družbo.',
                'V projektu RE-MIND TMNT sodeluje kot svetovalni in pilotni partner ter prispeva k vsem projektnim dejavnostim. Muzej ima dejavno vlogo v pobudah za vključevanje občinstva ter v delovnih sklopih 4 in 5 podpira izvajanje in potrjevanje modela krepitve zmogljivosti Čuječega muzeja. S preizkušanjem inovativnih izobraževalnih pristopov in vključevanjem različnih skupin obiskovalcev prispeva k razvoju čuječih, vključujočih in digitalno uravnoteženih muzejskih izkušenj.',
                'TMNT hrani zbirko več kot 11.000 predmetov kulturne dediščine ter ima dolgoletne izkušnje na področjih muzejske pedagogike, vključevanja javnosti in znanstvenega komuniciranja. V partnerstvu z univerzami, znanstvenimi središči, nevladnimi organizacijami ter strokovnjaki s področij znanosti, umetnosti in humanistike razvija inovativne izobraževalne programe. Kot soorganizator hrvaškega Festivala znanosti je prepoznan po spodbujanju interdisciplinarnega učenja, povezovanju znanosti s kulturo in razvoju v prihodnost usmerjenih muzejskih izkušenj, ki se odzivajo na spreminjajoče se družbene potrebe.',
                'TMNT je izvedel številne nacionalne in mednarodne projekte, ki spodbujajo socialno vključevanje, sodelovanje javnosti, enakost spolov in udeležbo manjšinskih skupin. Muzej dejavno podpira interdisciplinarne pristope k interpretaciji dediščine ter prek mednarodnih mrež in pobud, financiranih iz sredstev EU, sodeluje z evropskimi partnerji in prispeva k inovacijam v muzejski pedagogiki, dostopnosti in razvoju občinstva.',
            ],
        ],
        'brainster' => [
            'name' => 'Brainster',
            'bio' => [
                'Brainster je vodilna izobraževalno-tehnološka organizacija s sedežem v Skopju v Severni Makedoniji, ustanovljena leta 2015. S praktičnim izobraževanjem, usmerjenim v potrebe industrije, posameznikom omogoča pridobivanje spretnosti za prihodnost na področjih IT, umetne inteligence, digitalnega marketinga, oblikovanja in podjetništva. Organizacija je izobrazila več kot 14.000 udeležencev ter razvila inovativne digitalne učne rešitve, vključno z lastnim sistemom za upravljanje učenja in učno platformo, podprto z umetno inteligenco.',
                'V projektu RE-MIND Brainster vodi delovni sklop 6 za komuniciranje, razširjanje in trajnost ter skrbi za komunikacijsko strategijo projekta, vizualno identiteto, spletno stran, družbena omrežja in sodelovanje deležnikov. Prispeva tudi k razvoju Pametnega učnega ekosistema s podporo pri razvoju okvira za mikrodokazila in institucionalno potrditev. Z obsežnimi izkušnjami na področjih digitalnega izobraževanja, učnih tehnologij, komunikacijskih kampanj in evropskih projektov sodelovanja Brainster zagotavlja široko prepoznavnost, dolgoročno trajnost in pomemben učinek projektnih rezultatov po vsej Evropi.',
            ],
        ],
    ],
];
