<?php

return [
    'eyebrow' => 'Ljudi iza RE-MIND-a',
    'title' => 'KONZORCIJ',
    'contact_label' => 'Kontakt',
    'back_to_consortium' => 'Nazad na konzorcij',
    'intro_title' => 'SNAŽNO EVROPSKO PARTNERSTVO',
    'intro_paragraph' => 'RE-MIND okuplja 11 partnerskih organizacija iz 7 evropskih zemalja, ujedinjenih zajedničkom posvećenošću stvaranju svjesnijih, inkluzivnijih i angažiranijih muzejskih iskustava. Kroz prekograničnu saradnju, partneri iz Srbije, Italije, Hrvatske, Poljske, Slovenije, Bosne i Hercegovine i Sjeverne Makedonije doprinose svojom stručnošću, znanjem i kulturnim perspektivama podsticanju inovacija i trajnog uticaja širom evropskog muzejskog sektora.',

    'partners' => [
        'mei' => [
            'name' => 'MEI – Minds Europe – Institut za istraživačku izvrsnost i tehnološki napredak',
            'bio' => [
                'Minds Europe – Institut za istraživačku izvrsnost i tehnološki napredak (MEI) je nevladina, neprofitna organizacija za istraživanje i razvoj sa sjedištem u Novom Sadu, u Srbiji, osnovana 2020. godine. Djelujući kroz četiri strateška stuba – Mind-set KULTURA, PRIRODA, LJUDI i VI (vještačka inteligencija) – MEI povezuje akademsku izvrsnost s praktičnim društvenim inovacijama. Organizacija djeluje na sjecištu kulture, obrazovanja, digitalne transformacije, dobrobiti i inkluzivnog uključivanja zajednice, razvijajući metodologije zasnovane na istraživanjima, obrazovne programe i inovativna rješenja koja podržavaju održivi društveni razvoj i jačaju kapacitete kulturnih i obrazovnih institucija.',
                'Kao koordinator projekta RE-MIND, MEI vodi Radni paket 1: Upravljanje projektom i koordinacija, osiguravajući efikasnu implementaciju, finansijsko upravljanje, osiguranje kvaliteta i cjelokupno strateško usmjeravanje projekta. MEI također predvodi razvoj Nacrta svjesnog muzeja u okviru Radnog paketa 2 te doprinosi osmišljavanju programa obuke, obrazovnih resursa, međugeneracijskih radionica, prezentacijskih događaja i Kulturnih krugova (Culture Circles). Organizacija igra centralnu ulogu u integraciji istraživačkih nalaza u praktične alate za muzeje širom Evrope.',
                'MEI objedinjuje stručnost u oblastima svjesne prisutnosti, digitalne dobrobiti, smirene tehnologije, učešća u kulturi, obrazovanja, informaciono-komunikacijskih tehnologija (IKT) i interakcije čovjeka i računara. Organizacija razvija metodologije zasnovane na dokazima koje naučna istraživanja prevode u praktična rješenja za kulturna i obrazovna okruženja. Zahvaljujući bogatom iskustvu u interdisciplinarnim istraživanjima, izgradnji kapaciteta, digitalnom učenju i inovacijama, MEI podržava organizacije u stvaranju inkluzivnih, angažirajućih i digitalno uravnoteženih okruženja, istovremeno promovišući dobrobit i cjeloživotno učenje.',
                'MEI je koordinirao i učestvovao u brojnim evropskim projektima finansiranim kroz programe Kreativna Evropa, Horizont Evropa, Erasmus+ i IPA. Njegovo iskustvo obuhvata izgradnju kapaciteta, digitalno obrazovanje, učešće u kulturi, angažovanje zainteresovanih stranaka, procjenu učinka i inovacije. Organizacija je također doprinijela velikim međunarodnim inicijativama za evaluaciju, uključujući Expo 2020 Dubai i Novi Sad – Evropska prijestonica kulture.',
            ],
        ],
        'algebra' => [
            'name' => 'Univerzitet Algebra Bernays',
            'bio' => [
                'Univerzitet Algebra Bernays jedna je od vodećih privatnih visokoškolskih ustanova u Hrvatskoj i dio najveće privatne obrazovne organizacije u zemlji i regiji, koja od svog osnivanja 1998. godine djeluje u više od 20 gradova. Univerzitet je posvećen stvaranju inovativnog okruženja za učenje koje osnažuje studente, istraživače i stručnjake da postanu lideri u razvoju i primjeni digitalnih tehnologija. Njegova vizija je obrazovati etične inovatore i buduće pokretače promjena koji doprinose tehnološkom napretku i održivom društvenom razvoju.',
                'U okviru projekta RE-MIND, Univerzitet Algebra Bernays vodi Radni paket 3: Izgradnja RE-MIND pametnog ekosistema učenja za mikro-akreditaciju i institucionalnu podršku. Univerzitet je odgovoran za dizajniranje i razvoj projektne digitalne platforme za učenje, podržavanje integracije materijala za obuku u interaktivno online okruženje te doprinos razvoju okvira za mikro-akreditaciju. Također učestvuje u implementaciji projekta, aktivnostima validacije i širenju rezultata projekta.',
                'Univerzitet Algebra Bernays prepoznat je po svom multidisciplinarnom pristupu obrazovanja usmjerenom na studente te po snažnoj stručnosti u digitalnom učenju, dizajnu nastave i STEM oblastima. Univerzitet razvija inovativne obrazovne programe i integriše napredne metode podučavanja, uključujući poslovne simulacije i interaktivne tehnologije učenja. Kroz blisku saradnju s partnerima iz industrije i opsežno iskustvo u projektima digitalne transformacije, Univerzitet pruža stručnost potrebnu za razvoj visokokvalitetnih obrazovnih okruženja i podršku inovacijama u obrazovanju i stručnom usavršavanju.',
                'Univerzitet Algebra Bernays ima opsežno iskustvo u razvoju i implementaciji rješenja za digitalno obrazovanje i e-učenje za organizacije javnog i privatnog sektora. Univerzitet je uspješno realizovao projekte usmjerene na dizajn nastave, digitalnu transformaciju, mikro-akreditaciju i cjeloživotno učenje, kombinirajući stručnost u STEM-u, obrazovnim tehnologijama i inovativnim metodologijama učenja kako bi podržao profesionalni razvoj u različitim sektorima.',
            ],
        ],
        'adm' => [
            'name' => 'Archivio della Memoria (AdM)',
            'bio' => [
                'Archivio della Memoria (AdM) je italijanska neprofitna kulturna organizacija osnovana 2002. godine sa sjedištem u Rimu. Organizacija je specijalizirana za očuvanje i promociju kulturne baštine putem digitalnih tehnologija, usmene historije, audiovizuelnog pripovijedanja i participativnih obrazovnih pristupa. Od 2006. godine, AdM sarađuje sa Univerzitetom Tor Vergata u Rimu te je dio mreže Naučnog parka Tor Vergata. Kroz istraživanja, obuku i inicijative za podizanje svijesti, AdM sarađuje sa školama, univerzitetima, kulturnim institucijama i lokalnim zajednicama u cilju promovisanja cjeloživotnog učenja, društvene inkluzije, dobrobiti i aktivnog učešća u kulturi.',
                'U okviru projekta RE-MIND, Archivio della Memoria vodi Radni paket 2: Razvoj modela edukacije i dosega svjesnog muzeja i priručnika za obuku. Organizacija koordinira identifikaciju primjera dobre prakse, razvija priručnik za obuku projekta RE-MIND i multimedijalne obrazovne resurse te doprinosi aktivnostima izgradnje kapaciteta za muzejske stručnjake. AdM također podržava edukativne sesije, međugeneracijske radionice i aktivnosti širenja rezultata, pomažući u promociji svjesnih, inkluzivnih i digitalno uravnoteženih muzejskih iskustava.',
                'Archivio della Memoria ima bogato iskustvo u oblastima kulturne baštine, digitalnog pripovijedanja, audiovizuelne produkcije, participativnih istraživanja i obrazovnih inovacija. Tokom protekle dvije decenije, organizacija je realizovala oko 2.000 kvalitativnih video intervjua, kombinirajući usmenu historiju s metodologijama društvenog pripovijedanja. Njen multidisciplinarni tim ima značajno iskustvo u razvoju programa obuke, multimedijalnih obrazovnih resursa i kampanja za podizanje svijesti usmjerenih na digitalne inovacije, dobrobit, društvenu inkluziju i međugeneracijsko učenje kroz nacionalne i evropske inicijative.',
                'Archivio della Memoria učestvovala je u brojnim evropskim projektima u oblastima obrazovanja odraslih, stručnog obrazovanja i osposobljavanja, rada s mladima, školskog obrazovanja i kulturne baštine. Njeno iskustvo uključuje projekte CHART, DIST-SEED, Erasmediah, DataPro, ACCESS, DEED i SIATE, usmjerene na kulturnu baštinu, digitalnu osviještenost, mentalnu dobrobit, ekološku održivost, društvenu inkluziju i izgradnju kapaciteta kroz inovativne obrazovne metodologije.',
            ],
        ],
        'bmn' => [
            'name' => 'Balkanska mreža muzeja',
            'bio' => [
                'Balkanska mreža muzeja (BMN) je međunarodna mreža sa sjedištem u Sarajevu, u Bosni i Hercegovini, koja okuplja muzejske stručnjake i institucije iz više od 20 zemalja. Osnovana kao regionalni program muzejske saradnje 2006. godine, a formalno registrovana kao udruženje 2015. godine, BMN je narasla od 11 osnivačkih muzeja do mreže od preko 150 muzeja članova i 300 stručnjaka iz oblasti kulturne baštine. BMN promoviše saradnju, razmjenu znanja i profesionalni razvoj, te istovremeno slavi, čuva i dijeli bogatu i raznoliku kulturnu baštinu Balkana.',
                'U okviru projekta RE-MIND, BMN vodi Radni paket 5: Implementacija i validacija modela izgradnje kapaciteta Svjesnog muzeja te doprinosi svim ostalim radnim paketima. BMN koordinira organizaciju RE-MIND prezentacijskih događaja, priznavanje RE-MIND ambasadora i sistem podrške svjesnih muzeja, te validaciju Modela svjesnog muzeja i konačno usavršavanje edukativnih i informativnih okvira. Kroz svoju široku mrežu muzeja, BMN podržava vidljivost projekta, te njegovu primjenu i dugoročnu održivost.',
                'BMN je vodeća regionalna platforma za jačanje muzejske prakse kroz izgradnju kapaciteta, umrežavanje i saradničke projekte. Od 2010. godine podržala je više od 100 muzejskih inicijativa i trenutno upravlja Fondom Headley za kulturnu baštinu jugoistočne Evrope, ulažući u zaštitu baštine širom regije. BMN također promoviše pristupačnost i inkluziju putem svoje online baze podataka pristupačnih muzejskih usluga, objavila je 28 stručnih publikacija, organizovala 12 međunarodnih putujućih muzejskih konferencija te uspostavila prestižne nagrade kojima se prepoznaje izvrsnost u muzejskoj praksi i promociji kulturne baštine.',
                'BMN ima veliko iskustvo u evropskim projektima saradnje usmjerenim na pristupačnost, inkluziju i profesionalni razvoj u sektoru kulturne baštine. Kroz svoju Balkansku grupu za pristup muzejima (BMAG), podržava muzeje da postanu pristupačniji i inkluzivniji. BMN je učestvovala u Erasmus+ projektima kao što su Tomimeus i iNCLUSION, kao i u projektu SHIFT programa Horizont, doprinoseći stručnošću u izgradnji kapaciteta, umrežavanju i angažmanu publike.',
            ],
        ],
        'cwep' => [
            'name' => 'CWEP',
            'bio' => [
                'Centrum Wspierania Edukacji i Przedsiębiorczości (CWEP) je nevladina organizacija osnovana 2004. godine sa sjedištem u Rzeszówu, u Poljskoj. CWEP je posvećen promociji inovativnog obrazovanja, poduzetništva, naučnih istraživanja i održivog razvoja. Organizacija potiče cjeloživotno učenje, društvenu inkluziju i inovacije stvaranjem pristupačnih obrazovnih mogućnosti za osobe svih uzrasta. Kroz svoj rad, CWEP osnažuje pojedince i zajednice znanjem i vještinama potrebnim za prihvatanje digitalne transformacije, jačanje zapošljivosti, podršku odgovornom poduzetništvu i doprinos održivijem i inkluzivnijem društvu.',
                'U okviru projekta RE-MIND, CWEP vodi Radni paket 4: Obrazovanje i međugeneracijsko uključivanje publike u svjesnim muzejskim iskustvima. Organizacija je odgovorna za razvoj Smjernica za uključivanje publike, dizajniranje edukativnih sesija prilagođenih različitim generacijama te koordinaciju međugeneracijskih krugova učenja. U saradnji sa svim projektnim partnerima, CWEP doprinosi jačanju digitalne dobrobiti, svjesne prisutnosti i društvene inkluzije stvaranjem angažirajućih iskustava učenja koja podržavaju implementaciju RE-MIND modela svjesnog muzeja.',
                'CWEP posjeduje bogato iskustvo u razvoju obrazovnih programa, provođenju obuka i implementaciji evropskih projekata usmjerenih na digitalne vještine, poduzetništvo, društvenu inkluziju i održivost. Organizacija kombinuje stručnost u istraživanju, razvoju nastavnih planova i programa, izdavaštvu i komunikaciji kako bi stvorila inovativne resurse za učenje za različite ciljne grupe. Kroz brojne nacionalne i međunarodne inicijative, CWEP se pozicionirao kao pouzdan partner u promovisanju cjeloživotnog učenja, digitalnih inovacija i inkluzivnog obrazovanja, uz podršku razvoju vještina za budućnost.',
                'CWEP je učestvovao u brojnim projektima finansiranim od strane EU koji se bave digitalnim obrazovanjem, inkluzijom i cjeloživotnim učenjem. Njihovo nedavno iskustvo uključuje projekte MYCo, DIST-SEED, Mindfulness for Integration i SOURCE, s fokusom na međugeneracijsku saradnju, digitalno pripovijedanje, obrazovanje zasnovano na svjesnoj prisutnosti i inovativne metodologije podučavanja. Ovi projekti potvrđuju snažnu stručnost CWEP-a u razvoju obrazovnih resursa, programa izgradnje kapaciteta i inkluzivnih pristupa učenju.',
            ],
        ],
        'koda' => [
            'name' => 'Koda',
            'bio' => [
                'Koda je organizacija civilnog društva sa sjedištem u Ljubljani, u Sloveniji, specijalizirana za digitalnu kulturu, etičko korištenje tehnologije i inkluzivno digitalno učešće. Kroz virtuelne izložbe, digitalne kampanje i hibridna kulturna iskustva, Koda promoviše cjeloživotno učenje i osnažuje pojedince na navigaciju digitalnim svijetom s povjerenjem, kreativnošću i kritičkom sviješću. Organizacija djeluje na sjecištu kulture, obrazovanja i tehnologije, potičući odgovorno digitalno učešće i podržavajući inovacije koje su pristupačne, etične i društveno inkluzivne.',
                'U okviru projekta RE-MIND, Koda vodi aktivnosti Osiguranja kvalitete, etike i evaluacije, osiguravajući da implementacija projekta ostane usklađena sa standardima kvalitete, etičkim principima i ciljevima projekta. Organizacija razvija okvir za osiguranje kvalitete, etiku i evaluaciju, a istovremeno doprinosi razvoju RE-MIND priručnika za obuku, obrazovnih resursa i aktivnosti učenja. Kroz svoju stručnost u digitalnoj dobrobiti i odgovornim inovacijama, Koda podržava ostvarivanje visokokvalitetnih i inkluzivnih ishoda projekta.',
                'Koda posjeduje značajnu stručnost u oblastima digitalne kulture, etičke tehnologije, digitalne dobrobiti i inkluzivnog online učešća. Organizacija razvija inovativne obrazovne resurse, digitalne kampanje i participativne kulturne inicijative koje promovišu odgovornu upotrebu tehnologije i digitalnu inkluziju. Sa snažnim iskustvom u upravljanju projektima, kreativnoj komunikaciji i međusektorskoj saradnji, Koda podržava cjeloživotno učenje i osnažuje pojedince i organizacije da samouvjereno i etički djeluju u digitalnim okruženjima, istovremeno podstičući pristupačne i društveno odgovorne inovacije.',
                'Koda ima opsežno iskustvo u digitalnom obrazovanju, radu s mladima i izgradnji kapaciteta, sa snažnim fokusom na digitalnu pismenost, sigurnost na internetu, odgovornu upotrebu tehnologije i digitalnu dobrobit. Kroz nacionalne i međunarodne projekte, organizacija je razvijala obrazovne resurse, provodila obuke za mlade i stručnjake te sprovodila inicijative koje promovišu sigurno, inkluzivno i etičko digitalno učešće u različitim zajednicama.',
            ],
        ],
        'mov' => [
            'name' => 'Muzej Vojvodine (MoV)',
            'bio' => [
                'Muzej Vojvodine jedna je od vodećih kulturnih institucija u Srbiji, smještena u Novom Sadu, čiji počeci sežu do Srpske narodne zbirke osnovane u Budimpešti 1847. godine. Posvećen očuvanju i tumačenju bogatog kulturnog naslijeđa Vojvodine, Muzej kroz svoje zbirke i izložbe dokumentira preko 8.000 godina ljudske historije. U nastojanju da odgovori potrebama savremene publike, Muzej promoviše obrazovanje, inkluziju i cjeloživotno učenje, ohrabrujući posjetioce da bolje razumiju prošlost te ih inspirišući na aktivno uključivanje u sadašnjost i budućnost.',
                'U okviru projekta RE-MIND, Muzej Vojvodine doprinosi kao savjetodavni i pilot-partner, učestvujući u svim projektnim aktivnostima. Muzej igra ključnu ulogu u radnim paketima 4 i 5, podržavajući aktivnosti uključivanja publike te implementaciju i validaciju Modela izgradnje kapaciteta svjesnog muzeja. Kroz svoju stručnost u obrazovanju i blisku interakciju sa različitim grupama posjetilaca, Muzej doprinosi testiranju i unapređenju inovativnih pristupa svjesnim, inkluzivnim i međugeneracijskim muzejskim iskustvima.',
                'Muzej Vojvodine objedinjuje bogato stručno znanje iz arheologije, etnologije, historije i likovnih umjetnosti sa snažnom posvećenošću muzejskom obrazovanju i uključivanju publike. Njegov multidisciplinarni tim kustosa, konzervatora, istraživača i muzejskih edukatora razvija inovativne izložbe i obrazovne programe za posjetioce svih uzrasta. Aktivnim učešćem u istraživačkim projektima, međunarodnim konferencijama i profesionalnim mrežama, Muzej doprinosi unapređenju muzejske prakse te promoviše kulturnu baštinu kroz inkluzivna i angažirajuća iskustva učenja.',
                'Muzej Vojvodine ima značajno iskustvo u međunarodnoj saradnji ostvareno kroz zajedničke izložbe, istraživačke inicijative, programe kulturne razmjene i partnerstva s muzejima i institucijama kulturnog naslijeđa širom Evrope. Ove saradnje ojačale su njegovu stručnost u uključivanju publike, tumačenju naslijeđa i realizaciji projekata, potvrđujući njegovu ulogu aktivnog učesnika u međunarodnom kulturnom dijalogu i inovacijama u muzejskoj praksi.',
            ],
        ],
        'nimb' => [
            'name' => 'Nacionalna ustanova Zavod i muzej Bitola (NIMB)',
            'bio' => [
                'Nacionalna ustanova Zavod i muzej Bitola (NIMB) jedna je od vodećih institucija kulturne baštine u Sjevernoj Makedoniji, koja objedinjuje zaštitu, istraživanje i prezentaciju materijalne i nematerijalne kulturne baštine. Sa sjedištem u Bitoli, ustanova zapošljava multidisciplinarni tim arheologa, etnologa, historičara, historičara umjetnosti, konzervatora i muzejskih stručnjaka. Uz podršku Ministarstva kulture Sjeverne Makedonije, NIMB svake godine provodi više od 50 nacionalnih i međunarodnih projekata, promovišući očuvanje baštine, muzejsko obrazovanje, pristupačnost i javni angažman za raznoliku publiku.',
                'U okviru projekta RE-MIND, NIMB učestvuje kao demonstracijski i pilot-partner, doprinoseći implementaciji i validaciji Modela svjesnog muzeja. Institucija učestvuje u svim projektnim aktivnostima, podržavajući razvoj obrazovnih resursa, stručno osposobljavanje i interaktivne inicijative za uključivanje publike. Pilotiranjem pristupa zasnovanih na svjesnoj prisutnosti u muzejskom okruženju, NIMB pomaže u procjeni učinkovitosti modela u podsticanju digitalne dobrobiti, međugeneracijskog dijaloga i društveno odgovornih muzejskih iskustava.',
                'Sa više od 90 godina neprekidnog rada, NIMB ima opsežno iskustvo u muzejskom obrazovanju, pristupačnosti, tumačenju kulturne baštine i upravljanju međunarodnim projektima. Ustanova ima preko dvije decenije iskustva u obrazovnom programiranju i više od deset godina predanog rada na unapređenju pristupačnosti za raznoliku publiku. Svojim inkluzivnim izložbama, inovativnim obrazovnim inicijativama i jakim partnerstvima, NIMB promoviše jednak pristup kulturnoj baštini, istovremeno unapređujući savremene muzejske prakse i angažman zajednice.',
                'NIMB godišnje provodi više od 50 projekata u oblastima zaštite naslijeđa, muzejskog tumačenja, obrazovanja i pristupačnosti. Ustanova upravlja značajnim lokalitetima kulturne baštine, uključujući Herakleja Lyncestis, te je vodila inicijative za pristupačnost, razvila međunarodno izlagane taktilne izložbe i intenzivno sarađivala s evropskim partnerima. Kao aktivni član međunarodnih muzejskih mreža, NIMB primjenjuje evropske standarde u očuvanju baštine, inkluziji i održivom kulturnom turizmu.',
            ],
        ],
        'spac' => [
            'name' => 'SPAC — Scuola nazionale del patrimonio e delle attività culturali',
            'bio' => [
                'Scuola nazionale del patrimonio e delle attività culturali (Scuola) je italijanska institucija sa sjedištem u Rimu, osnovana 2015. godine od strane Ministarstva kulture radi promovisanja kontinuiranog profesionalnog razvoja stručnjaka za kulturnu baštinu. Kao međunarodni centar za obuku, istraživanje i inovacije, Scuola podržava transformaciju kulturnog sektora kroz interdisciplinarno učenje, primijenjena istraživanja i međunarodnu saradnju. Njeno djelovanje usmjereno je na upravljanje baštinom, digitalnu transformaciju, pristupačnost i inkluziju, podstičući razmjenu znanja i jačanje profesionalnih kapaciteta u cjelokupnom ekosistemu kulturne baštine.',
                'U okviru projekta RE-MIND, Scuola učestvuje kao demonstracijski i pilot-partner, doprinoseći zajedničkom stvaranju, implementaciji, testiranju i validaciji Modela izgradnje kapaciteta svjesnog muzeja. Organizacija aktivno učestvuje u operativnim radnim paketima projekta, podržavajući programe obuke, radionice i aktivnosti validacije. Scuola također doprinosi širenju rezultata i angažiranju zainteresovanih aktera putem svojih opsežnih nacionalnih i međunarodnih mreža te koordinira organizaciju RE-MIND prezentacijskog događaja u Italiji.',
                'Scuola posjeduje značajnu stručnost u osmišljanju i provođenju programa profesionalnog razvoja za stručnjake iz muzeja, arhiva, biblioteka i sektora kulturne baštine. Razvija inovativne mogućnosti učenja kroz formate uživo, online i u mješovitom obliku, pružajući podršku menadžerima muzeja, javnim službenicima, donosiocima odluka i stručnjacima za baštinu. Kroz blisku saradnju s italijanskim Ministarstvom kulture i međunarodnim organizacijama, Scuola je izgradila snažnu stručnost u upravljanju baštinom, digitalnoj transformaciji, pristupačnosti, međunarodnoj saradnji i cjeloživotnom učenju, pomažući u jačanju kulturnog sektora kroz razmjenu znanja i izgradnju kapaciteta.',
                'Scuola je učestvovala u brojnim evropskim i međunarodnim inicijativama usmjerenim na razvoj vještina i inovacije u oblasti kulturne baštine, uključujući projekat CHARTER Erasmus+ Blueprint, saradnju u okviru programa Horizont Evrope te Dicolab, italijanski nacionalni program za digitalne vještine u kulturnom sektoru. Također provodi međunarodne programe izgradnje kapaciteta za stručnjake iz oblasti kulturne baštine i upravlja platformom za digitalno učenje koja opslužuje više od 34.000 korisnika.',
            ],
        ],
        'tmnt' => [
            'name' => 'Tehnički muzej Nikola Tesla (TMNT)',
            'bio' => [
                'Tehnički muzej Nikola Tesla (TMNT) nalazi se u Zagrebu, u Hrvatskoj, a osnovan je 1954. godine kao vodeći muzej u zemlji posvećen nauci, tehnologiji i industrijskoj baštini. Smješten u prepoznatljivom arhitektonskom kompleksu koji je projektovao poznati hrvatski arhitekta Marijan Haberle, muzej čuva i predstavlja hrvatsko naučno i tehnološko naslijeđe kroz inovativne izložbe i obrazovne programe. Kao jedan od najposjećenijih muzeja u zemlji, TMNT aktivno promoviše cjeloživotno učenje, uključivanje javnosti i interdisciplinarnu saradnju, stvarajući interaktivna iskustva koja povezuju nauku, kulturu i društvo.',
                'U okviru projekta RE-MIND, TMNT učestvuje kao savjetodavni i pilot-partner, doprinoseći svim projektnim aktivnostima. Muzej igra aktivnu ulogu u inicijativama za uključivanje publike i podržava implementaciju i validaciju Modela izgradnje kapaciteta svjesnog muzeja u okviru Radnih paketa 4 i 5. Testiranjem inovativnih obrazovnih pristupa i uključivanjem različitih grupa posjetilaca, TMNT doprinosi razvoju svjesnih, inkluzivnih i digitalno uravnoteženih muzejskih iskustava.',
                'TMNT sadrži kolekciju od preko 11.000 predmeta kulturne baštine te posjeduje dugogodišnje iskustvo u muzejskom obrazovanju, javnom angažmanu i popularizaciji nauke. Muzej razvija inovativne obrazovne programe u saradnji s univerzitetima, naučnim centrima, nevladinim organizacijama i stručnjacima iz oblasti nauke, umjetnosti i humanističkih nauka. Kao suorganizator Festivala nauke u Hrvatskoj, TMNT je prepoznat po promovisanju interdisciplinarnog učenja, povezivanju nauke i kulture te razvoju muzejskih iskustava usmjerenih ka budućnosti koja odgovaraju na evoluirajuće potrebe društva.',
                'TMNT je implementirao brojne nacionalne i međunarodne projekte koji promovišu društvenu inkluziju, angažman javnosti, rodnu ravnopravnost i učešće manjinskih grupa. Muzej aktivno podržava interdisciplinarne pristupe tumačenju baštine i sarađuje s evropskim partnerima putem međunarodnih mreža i inicijativa koje finansira EU, doprinoseći inovacijama u muzejskom obrazovanju, pristupačnosti i razvoju publike.',
            ],
        ],
        'brainster' => [
            'name' => 'Brainster',
            'bio' => [
                'Brainster je vodeća organizacija za obrazovnu tehnologiju sa sjedištem u Skoplju, u Sjevernoj Makedoniji, osnovana 2015. godine. Kroz praktično obrazovanje usmjereno na potrebe tržišta rada, Brainster osnažuje pojedince vještinama potrebnim za budućnost u oblastima IT-ja, vještačke inteligencije, digitalnog marketinga, dizajna i poduzetništva. Organizacija je edukovala više od 14.000 učenika te razvila inovativna digitalna rješenja za učenje, uključujući vlastiti sistem za upravljanje učenjem i platformu za učenje zasnovanu na vještačkoj inteligenciji.',
                'U projektu RE-MIND, Brainster vodi Radni paket 6: Komunikacija, širenje rezultata i održivosti, nadgledajući komunikacijsku strategiju projekta, vizualni identitet, web-stranicu, društvene mreže i angažiranje zainteresovanih strana. Brainster također doprinosi razvoju pametnog ekosistema učenja podržavajući okvir za mikro-akreditacije i institucionalnu podršku. Zahvaljujući bogatom iskustvu u digitalnom obrazovanju, tehnologijama za učenje, komunikacijskim kampanjama i evropskim projektima saradnje, Brainster osigurava široku vidljivost projektnih rezultata, njihovu dugoročnu održivost i značajan utjecaj širom Evrope.',
            ],
        ],
    ],
];
