<?php

return [
    'eyebrow' => 'Le persone dietro RE-MIND',
    'title' => 'CONSORZIO',
    'contact_label' => 'Contatti',
    'back_to_consortium' => 'Torna al Consorzio',
    'intro_title' => 'UN FORTE PARTENARIATO EUROPEO',
    'intro_paragraph' => 'RE-MIND riunisce 11 organizzazioni partner provenienti da 7 paesi europei, unite da un impegno condiviso nel creare esperienze museali più consapevoli, inclusive e coinvolgenti. Attraverso la collaborazione transfrontaliera, i partner di Serbia, Italia, Croazia, Polonia, Slovenia, Bosnia ed Erzegovina e Macedonia del Nord contribuiscono con la loro competenza, conoscenza e prospettive culturali per promuovere l\'innovazione e un impatto duraturo nel settore museale europeo.',

    'partners' => [
        'mei' => [
            'name' => 'MEI – Minds Europe – Institute for Research Excellence and Technological Advancement',
            'bio' => [
                "Minds Europe – Institute for Research Excellence and Technological Advancement (MEI) è un'organizzazione non governativa e senza scopo di lucro di ricerca e sviluppo con sede a Novi Sad, Serbia, fondata nel 2020. Operando attraverso quattro pilastri strategici — Mind-set CULTURE, NATURE, PEOPLE e AI — MEI collega l'eccellenza accademica all'innovazione sociale pratica. L'organizzazione opera all'intersezione tra cultura, educazione, trasformazione digitale, benessere e coinvolgimento inclusivo delle comunità, sviluppando metodologie basate sulla ricerca, programmi educativi e soluzioni innovative che sostengono lo sviluppo sociale sostenibile e rafforzano le capacità delle istituzioni culturali ed educative.",
                "In qualità di coordinatore del progetto RE-MIND, MEI guida il Work Package 1: Gestione e coordinamento del progetto, garantendo un'attuazione efficace, la gestione finanziaria, l'assicurazione della qualità e l'orientamento strategico complessivo del progetto. MEI guida inoltre lo sviluppo del Mindful Museum Blueprint nell'ambito del Work Package 2 e contribuisce alla progettazione del programma formativo, delle risorse educative, dei workshop intergenerazionali, degli Showroom Event e dei Culture Circles. L'organizzazione svolge un ruolo centrale nel tradurre i risultati della ricerca in strumenti pratici per i musei europei.",
                "MEI combina competenze in mindfulness, benessere digitale, calm technology, partecipazione culturale, educazione, ICT e interazione uomo-computer. L'organizzazione sviluppa metodologie basate su evidenze che traducono la ricerca scientifica in soluzioni pratiche per contesti culturali ed educativi. Grazie a una vasta esperienza nella ricerca interdisciplinare, nel capacity building, nell'apprendimento digitale e nell'innovazione, MEI supporta le organizzazioni nella creazione di ambienti inclusivi, coinvolgenti ed equilibrati dal punto di vista digitale, promuovendo al contempo il benessere e l'apprendimento permanente.",
                "MEI ha coordinato e partecipato a numerosi progetti europei finanziati dai programmi Creative Europe, Horizon Europe, Erasmus+ e IPA. La sua esperienza comprende capacity building, educazione digitale, partecipazione culturale, coinvolgimento degli stakeholder, valutazione dell'impatto e innovazione. L'organizzazione ha inoltre contribuito a importanti iniziative internazionali di valutazione, tra cui Expo 2020 Dubai e Novi Sad Capitale Europea della Cultura.",
            ],
        ],
        'algebra' => [
            'name' => 'Algebra Bernays University',
            'bio' => [
                "Algebra Bernays University è una delle principali istituzioni private di istruzione superiore della Croazia e fa parte della più grande organizzazione educativa privata del Paese e della regione, attiva in oltre 20 città dalla sua fondazione nel 1998. L'Università si impegna a creare un ambiente di apprendimento innovativo che consenta a studenti, ricercatori e professionisti di diventare protagonisti nello sviluppo e nell'applicazione delle tecnologie digitali. La sua visione è formare innovatori etici e futuri agenti del cambiamento capaci di contribuire al progresso tecnologico e allo sviluppo sostenibile della società.",
                "Nell'ambito del progetto RE-MIND, Algebra Bernays University guida il Work Package 3: Costruzione dello Smart Learning Ecosystem RE-MIND per le micro-credenziali e il riconoscimento istituzionale. L'Università è responsabile della progettazione e dello sviluppo della piattaforma digitale di apprendimento del progetto, supporta l'integrazione dei materiali formativi in un ambiente online interattivo e contribuisce allo sviluppo del framework per le micro-credenziali. Partecipa inoltre all'implementazione del progetto, alle attività di validazione e alla diffusione dei risultati.",
                "Algebra Bernays University è riconosciuta per il suo approccio multidisciplinare e centrato sullo studente e per la sua solida esperienza nell'apprendimento digitale, nell'instructional design e nelle discipline STEM. L'Università sviluppa programmi educativi innovativi e integra metodi didattici avanzati, tra cui simulazioni aziendali e tecnologie di apprendimento interattive. Grazie alla stretta collaborazione con partner industriali e alla vasta esperienza nei progetti di trasformazione digitale, l'Università offre le competenze necessarie per sviluppare ambienti di apprendimento di alta qualità e sostenere l'innovazione nell'educazione e nella formazione professionale.",
                "Algebra Bernays University vanta una vasta esperienza nello sviluppo e nell'implementazione di soluzioni di educazione digitale ed e-learning per organizzazioni del settore pubblico e privato. Ha realizzato con successo progetti dedicati all'instructional design, alla trasformazione digitale, alle micro-credenziali e all'apprendimento permanente, combinando competenze STEM, tecnologie educative e metodologie didattiche innovative per sostenere lo sviluppo professionale in diversi settori.",
            ],
        ],
        'adm' => [
            'name' => 'Archivio della Memoria (AdM)',
            'bio' => [
                "Archivio della Memoria (AdM) è un'organizzazione culturale italiana senza scopo di lucro fondata nel 2002 e con sede a Roma. L'organizzazione è specializzata nella conservazione e valorizzazione del patrimonio culturale attraverso tecnologie digitali, storia orale, storytelling audiovisivo e approcci educativi partecipativi. Dal 2006 AdM ha collaborato con l'Università degli Studi di Roma Tor Vergata e fa parte della rete del Parco Scientifico di Tor Vergata. Attraverso iniziative di ricerca, formazione e sensibilizzazione, AdM collabora con scuole, università, istituzioni culturali e comunità locali per promuovere l'apprendimento permanente, l'inclusione sociale, il benessere e la partecipazione culturale attiva.",
                "Nell'ambito del progetto RE-MIND, Archivio della Memoria guida il Work Package 2: Sviluppo del Modello di Educazione e Outreach del Museo Mindful e del Toolkit formativo. L'organizzazione coordina l'identificazione delle buone pratiche, sviluppa il toolkit formativo RE-MIND e le risorse didattiche multimediali e contribuisce alle attività di capacity building per i professionisti museali. AdM supporta inoltre sessioni educative, workshop intergenerazionali e attività di disseminazione, contribuendo a promuovere esperienze museali mindful, inclusive ed equilibrate dal punto di vista digitale.",
                "Archivio della Memoria possiede una vasta esperienza nel patrimonio culturale, nello storytelling digitale, nella produzione audiovisiva, nella ricerca partecipativa e nell'innovazione educativa. Negli ultimi due decenni, l'organizzazione ha prodotto circa 2.000 video-interviste qualitative, combinando la storia orale con metodologie di storytelling sociale. Il suo team multidisciplinare vanta una significativa esperienza nello sviluppo di programmi formativi, risorse educative multimediali e campagne di sensibilizzazione incentrate su innovazione digitale, benessere, inclusione sociale e apprendimento intergenerazionale, attraverso iniziative nazionali ed europee.",
                "Archivio della Memoria ha partecipato a numerosi progetti europei nei settori dell'educazione degli adulti, dell'istruzione e formazione professionale, della gioventù, della scuola e del patrimonio culturale. La sua esperienza comprende progetti quali CHART, DIST-SEED, Erasmediah, DataPro, ACCESS, DEED e SIATE, dedicati al patrimonio culturale, alla consapevolezza digitale, al benessere mentale, alla sostenibilità ambientale, all'inclusione sociale e al capacity building attraverso metodologie educative innovative.",
            ],
        ],
        'bmn' => [
            'name' => 'Balkan Museum Network',
            'bio' => [
                'Balkan Museum Network (BMN) è una rete internazionale con sede a Sarajevo, Bosnia-Erzegovina, che riunisce professionisti e istituzioni museali di oltre 20 Paesi. Nata nel 2006 come programma regionale di collaborazione museale e formalmente registrata come associazione nel 2015, BMN è cresciuta dagli 11 musei fondatori fino a comprendere oltre 150 musei membri e 300 professionisti del patrimonio. BMN promuove la cooperazione, lo scambio di conoscenze e lo sviluppo professionale, valorizzando, preservando e condividendo il ricco e diversificato patrimonio culturale dei Balcani.',
                "Nel progetto RE-MIND, BMN guida il Work Package 5: Implementazione e validazione del Modello di Capacity Building del Museo Mindful e contribuisce a tutti gli altri work package. BMN coordina l'organizzazione degli Showroom Event RE-MIND, il riconoscimento degli Ambasciatori RE-MIND e il sistema di endorsement Mindful Museum, la validazione del Modello di Museo Mindful e il perfezionamento finale del framework educativo e di outreach. Attraverso la sua vasta rete museale, BMN sostiene la visibilità, l'adozione e la sostenibilità a lungo termine del progetto.",
                "BMN è una piattaforma regionale di riferimento per il rafforzamento delle pratiche museali attraverso capacity building, networking e progetti collaborativi. Dal 2010 ha sostenuto oltre 100 iniziative museali e attualmente gestisce l'Headley Southeast Europe Cultural Heritage Fund, investendo nella protezione del patrimonio della regione. BMN promuove inoltre accessibilità e inclusione attraverso una banca dati online dei servizi museali accessibili, ha pubblicato 28 pubblicazioni professionali, organizzato 12 conferenze museali internazionali itineranti e istituito prestigiosi premi per riconoscere l'eccellenza nella pratica museale e nella promozione del patrimonio culturale.",
                'BMN vanta una vasta esperienza in progetti di cooperazione europea dedicati ad accessibilità, inclusione e sviluppo professionale nel settore del patrimonio culturale. Attraverso il Balkan Museum Access Group (BMAG), sostiene i musei nel diventare più accessibili e inclusivi. BMN ha partecipato a progetti Erasmus+ quali Tomimeus e iNCLUSION e al progetto Horizon SHIFT, contribuendo con competenze in capacity building, networking e coinvolgimento dei pubblici.',
            ],
        ],
        'cwep' => [
            'name' => 'CWEP',
            'bio' => [
                'Centrum Wspierania Edukacji i Przedsiębiorczości (CWEP) è un\'organizzazione non governativa fondata nel 2004 e con sede a Rzeszów, Polonia. CWEP è impegnata nella promozione dell\'educazione innovativa, dell\'imprenditorialità, della ricerca scientifica e dello sviluppo sostenibile. L\'organizzazione favorisce l\'apprendimento permanente, l\'inclusione sociale e l\'innovazione creando opportunità educative accessibili a persone di tutte le età. Attraverso le proprie attività, CWEP fornisce a individui e comunità conoscenze e competenze per affrontare la trasformazione digitale, rafforzare l\'occupabilità, sostenere un\'imprenditorialità responsabile e contribuire a una società più sostenibile e inclusiva.',
                "Nel progetto RE-MIND, CWEP guida il Work Package 4: Educazione e coinvolgimento intergenerazionale dei pubblici nelle esperienze del Museo Mindful. L'organizzazione è responsabile dello sviluppo delle Linee guida per il coinvolgimento dei pubblici, della progettazione di sessioni educative adattate alle diverse generazioni e del coordinamento dei circoli di apprendimento intergenerazionale. In collaborazione con tutti i partner, CWEP contribuisce a rafforzare il benessere digitale, la mindfulness e l'inclusione sociale attraverso esperienze di apprendimento coinvolgenti che sostengono l'implementazione del Modello di Museo Mindful RE-MIND.",
                "CWEP possiede una vasta esperienza nello sviluppo di programmi educativi, nell'erogazione di formazione e nell'attuazione di progetti europei dedicati a competenze digitali, imprenditorialità, inclusione sociale e sostenibilità. L'organizzazione combina competenze in ricerca, sviluppo curricolare, editoria e comunicazione per creare risorse di apprendimento innovative rivolte a gruppi target diversi. Attraverso numerose iniziative nazionali e internazionali, CWEP si è affermata come partner affidabile nella promozione dell'apprendimento permanente, dell'innovazione digitale e dell'educazione inclusiva.",
                "CWEP ha partecipato a numerosi progetti finanziati dall'UE dedicati all'educazione digitale, all'inclusione e all'apprendimento permanente. Tra le esperienze più recenti figurano MYCo, DIST-SEED, Mindfulness for Integration e SOURCE, incentrati sulla cooperazione intergenerazionale, lo storytelling digitale, l'educazione basata sulla mindfulness e metodologie didattiche innovative. Questi progetti dimostrano la solida esperienza di CWEP nello sviluppo di risorse educative, programmi di capacity building e approcci inclusivi all'apprendimento.",
            ],
        ],
        'koda' => [
            'name' => 'Koda',
            'bio' => [
                "Koda è un'organizzazione della società civile con sede a Lubiana, Slovenia, specializzata in cultura digitale, uso etico della tecnologia e coinvolgimento digitale inclusivo. Attraverso mostre virtuali, campagne digitali ed esperienze culturali ibride, Koda promuove l'apprendimento permanente e consente alle persone di orientarsi nel mondo digitale con sicurezza, creatività e consapevolezza critica. L'organizzazione opera all'intersezione tra cultura, educazione e tecnologia, promuovendo una partecipazione digitale responsabile e sostenendo un'innovazione accessibile, etica e socialmente inclusiva.",
                "Nel progetto RE-MIND, Koda guida le attività di Assicurazione della qualità, Etica e Valutazione, garantendo che l'attuazione del progetto rimanga allineata agli standard di qualità, ai principi etici e agli obiettivi progettuali. L'organizzazione sviluppa il framework di Assicurazione della qualità, Etica e Valutazione e contribuisce al toolkit formativo RE-MIND, alle risorse educative e alle attività di apprendimento. Grazie alle proprie competenze in materia di benessere digitale e innovazione responsabile, Koda sostiene la realizzazione di risultati progettuali di alta qualità e inclusivi.",
                "Koda possiede una vasta esperienza in cultura digitale, tecnologia etica, benessere digitale e partecipazione online inclusiva. L'organizzazione sviluppa risorse educative innovative, campagne digitali e iniziative culturali partecipative che promuovono un uso responsabile della tecnologia e l'inclusione digitale. Grazie a una solida esperienza nella gestione di progetti, nella comunicazione creativa e nella collaborazione intersettoriale, Koda sostiene l'apprendimento permanente e aiuta individui e organizzazioni a partecipare agli ambienti digitali in modo sicuro ed etico, promuovendo un'innovazione accessibile e socialmente responsabile.",
                "Koda vanta una vasta esperienza nell'educazione digitale, nel lavoro con i giovani e nel capacity building, con particolare attenzione all'alfabetizzazione digitale, alla sicurezza online, all'uso responsabile della tecnologia e al benessere digitale. Attraverso progetti nazionali e internazionali, l'organizzazione ha sviluppato risorse educative, erogato formazione per giovani e professionisti e realizzato iniziative che promuovono una partecipazione digitale sicura, inclusiva ed etica in comunità diverse.",
            ],
        ],
        'mov' => [
            'name' => 'Museum of Vojvodina (MoV)',
            'bio' => [
                "Il Museum of Vojvodina è una delle principali istituzioni culturali della Serbia, con sede a Novi Sad e origini che risalgono alla Collezione Nazionale Serba fondata a Budapest nel 1847. Dedicato alla conservazione e all'interpretazione del ricco patrimonio culturale della regione della Vojvodina, il Museo documenta oltre 8.000 anni di storia umana attraverso le sue vaste collezioni ed esposizioni. Impegnato a rispondere alle esigenze dei pubblici contemporanei, il Museo promuove l'educazione, l'inclusione e l'apprendimento permanente, incoraggiando i visitatori a comprendere meglio il passato e a partecipare attivamente al presente e al futuro.",
                'Nel progetto RE-MIND, il Museum of Vojvodina contribuisce come partner consultivo e pilota, partecipando a tutte le attività progettuali. Il Museo svolge un ruolo chiave nei Work Package 4 e 5, sostenendo le attività di coinvolgimento dei pubblici e l\'implementazione e validazione del Modello di Capacity Building del Museo Mindful. Grazie alle proprie competenze educative e alla stretta interazione con diversi gruppi di visitatori, il Museo contribuisce a testare e perfezionare approcci innovativi a esperienze museali mindful, inclusive e intergenerazionali.',
                'Il Museum of Vojvodina combina una vasta esperienza in archeologia, etnologia, storia e belle arti con un forte impegno nell\'educazione museale e nel coinvolgimento dei pubblici. Il suo team multidisciplinare di curatori, conservatori, ricercatori ed educatori museali sviluppa mostre e programmi educativi innovativi per visitatori di tutte le età. Attraverso la partecipazione attiva a progetti di ricerca, conferenze internazionali e reti professionali, il Museo contribuisce all\'evoluzione delle pratiche museali, promuovendo il patrimonio culturale attraverso esperienze di apprendimento inclusive e coinvolgenti.',
                'Il Museum of Vojvodina vanta una vasta esperienza nella cooperazione internazionale attraverso mostre congiunte, iniziative di ricerca, programmi di scambio culturale e partenariati con musei e istituzioni del patrimonio in tutta Europa. Queste collaborazioni hanno rafforzato le sue competenze nel coinvolgimento dei pubblici, nell\'interpretazione del patrimonio e nell\'attuazione di progetti, consolidandone il ruolo di attore attivo nel dialogo culturale internazionale e nell\'innovazione museale.',
            ],
        ],
        'nimb' => [
            'name' => 'National Institution Institute and Museum Bitola (NIMB)',
            'bio' => [
                "La National Institution Institute and Museum Bitola (NIMB) è una delle principali istituzioni del patrimonio culturale della Macedonia del Nord e integra la protezione, la ricerca e la presentazione del patrimonio culturale materiale e immateriale. Con sede a Bitola, l'istituzione impiega un team multidisciplinare di archeologi, etnologi, storici, storici dell'arte, conservatori e professionisti museali. Con il sostegno del Ministero della Cultura della Macedonia del Nord, NIMB realizza ogni anno oltre 50 progetti nazionali e internazionali, promuovendo la conservazione del patrimonio, l'educazione museale, l'accessibilità e il coinvolgimento di pubblici diversi.",
                'Nel progetto RE-MIND, NIMB partecipa come partner dimostrativo e pilota, contribuendo all\'implementazione e alla validazione del Modello di Museo Mindful. L\'istituzione prende parte a tutte le attività progettuali, sostenendo lo sviluppo di risorse educative, la formazione professionale e iniziative interattive di coinvolgimento dei pubblici. Sperimentando approcci basati sulla mindfulness in un contesto museale, NIMB contribuisce a valutare l\'efficacia del modello nel promuovere il benessere digitale, il dialogo intergenerazionale ed esperienze museali socialmente responsabili.',
                'Con oltre 90 anni di attività continuativa, NIMB possiede una vasta esperienza nell\'educazione museale, nell\'accessibilità, nell\'interpretazione del patrimonio culturale e nella gestione di progetti internazionali. L\'istituzione vanta oltre vent\'anni di esperienza nella programmazione educativa e più di dieci anni di lavoro specifico per migliorare l\'accessibilità per pubblici diversi. Attraverso mostre inclusive, iniziative educative innovative e solide partnership, NIMB promuove un accesso equo al patrimonio culturale, contribuendo al progresso delle pratiche museali contemporanee e al coinvolgimento delle comunità.',
                'NIMB realizza oltre 50 progetti all\'anno nei settori della protezione del patrimonio, dell\'interpretazione museale, dell\'educazione e dell\'accessibilità. L\'istituzione gestisce importanti siti del patrimonio culturale, tra cui Heraclea Lyncestis, ha guidato iniziative per l\'accessibilità, sviluppato mostre tattili presentate a livello internazionale e collaborato ampiamente con partner europei. In qualità di membro attivo di reti museali internazionali, NIMB applica standard europei nella conservazione del patrimonio, nell\'inclusione e nel turismo culturale sostenibile.',
            ],
        ],
        'spac' => [
            'name' => 'SPAC — Scuola nazionale del patrimonio e delle attività culturali',
            'bio' => [
                'La Scuola nazionale del patrimonio e delle attività culturali (Scuola) è un\'istituzione italiana con sede a Roma, istituita nel 2015 dal Ministero della Cultura per promuovere lo sviluppo professionale continuo degli operatori del patrimonio culturale. In qualità di centro internazionale di formazione, ricerca e innovazione, la Scuola sostiene la trasformazione del settore culturale attraverso l\'apprendimento interdisciplinare, la ricerca applicata e la cooperazione internazionale. Le sue attività si concentrano sulla gestione del patrimonio, la trasformazione digitale, l\'accessibilità e l\'inclusione, favorendo lo scambio di conoscenze e il rafforzamento delle capacità professionali nell\'intero ecosistema del patrimonio culturale.',
                'Nel progetto RE-MIND, la Scuola partecipa come partner dimostrativo e pilota, contribuendo alla co-creazione, implementazione, sperimentazione e validazione del Modello di Capacity Building del Museo Mindful. L\'organizzazione è attivamente coinvolta nei work package operativi del progetto, sostenendo programmi formativi, workshop e attività di validazione. La Scuola contribuisce inoltre alla disseminazione e al coinvolgimento degli stakeholder attraverso le proprie vaste reti nazionali e internazionali e coordina l\'organizzazione di uno Showroom Event RE-MIND in Italia.',
                'La Scuola possiede una vasta esperienza nella progettazione e nell\'erogazione di programmi di sviluppo professionale per operatori di musei, archivi, biblioteche e del patrimonio culturale. Sviluppa opportunità di apprendimento innovative in presenza, online e in modalità blended, rivolte a direttori museali, funzionari pubblici, decisori politici e professionisti del patrimonio. Collaborando strettamente con il Ministero della Cultura italiano e con organizzazioni internazionali, la Scuola ha sviluppato solide competenze nella gestione del patrimonio, nella trasformazione digitale, nell\'accessibilità, nella cooperazione internazionale e nell\'apprendimento permanente.',
                'La Scuola ha partecipato a numerose iniziative europee e internazionali dedicate allo sviluppo delle competenze e all\'innovazione nel patrimonio culturale, tra cui il progetto Blueprint Erasmus+ CHARTER, collaborazioni Horizon Europe e Dicolab, il programma nazionale italiano per le competenze digitali nel settore culturale. Realizza inoltre programmi internazionali di capacity building per professionisti del patrimonio e gestisce una piattaforma di apprendimento digitale con oltre 34.000 utenti.',
            ],
        ],
        'tmnt' => [
            'name' => 'Technical Museum Nikola Tesla (TMNT)',
            'bio' => [
                'Il Technical Museum Nikola Tesla (TMNT) ha sede a Zagabria, Croazia, ed è stato fondato nel 1954 come principale museo del Paese dedicato alla scienza, alla tecnologia e al patrimonio industriale. Ospitato in un complesso architettonico di rilievo progettato dal celebre architetto croato Marijan Haberle, il museo conserva e presenta il patrimonio scientifico e tecnologico della Croazia attraverso mostre e programmi educativi innovativi. Tra i musei più visitati del Paese, TMNT promuove attivamente l\'apprendimento permanente, il coinvolgimento del pubblico e la collaborazione interdisciplinare, creando esperienze interattive che collegano scienza, cultura e società.',
                'Nel progetto RE-MIND, TMNT partecipa come partner consultivo e pilota, contribuendo a tutte le attività progettuali. Il museo svolge un ruolo attivo nelle iniziative di coinvolgimento dei pubblici e sostiene l\'implementazione e la validazione del Modello di Capacity Building del Museo Mindful nell\'ambito dei Work Package 4 e 5. Attraverso la sperimentazione di approcci educativi innovativi e il coinvolgimento di diversi gruppi di visitatori, TMNT contribuisce allo sviluppo di esperienze museali mindful, inclusive ed equilibrate dal punto di vista digitale.',
                'TMNT conserva una collezione di oltre 11.000 beni culturali e vanta una lunga esperienza nell\'educazione museale, nel coinvolgimento del pubblico e nella comunicazione scientifica. Il museo sviluppa programmi educativi innovativi in collaborazione con università, centri scientifici, ONG ed esperti nei campi della scienza, dell\'arte e delle discipline umanistiche. In qualità di co-organizzatore del Festival della Scienza della Croazia, TMNT è riconosciuto per la promozione dell\'apprendimento interdisciplinare, la connessione tra scienza e cultura e lo sviluppo di esperienze museali orientate al futuro e capaci di rispondere alle esigenze sociali in evoluzione.',
                'TMNT ha realizzato numerosi progetti nazionali e internazionali dedicati alla promozione dell\'inclusione sociale, del coinvolgimento del pubblico, dell\'uguaglianza di genere e della partecipazione dei gruppi minoritari. Il museo sostiene attivamente approcci interdisciplinari all\'interpretazione del patrimonio e collabora con partner europei attraverso reti internazionali e iniziative finanziate dall\'UE, contribuendo all\'innovazione nell\'educazione museale, nell\'accessibilità e nello sviluppo dei pubblici.',
            ],
        ],
        'brainster' => [
            'name' => 'Brainster',
            'bio' => [
                'Brainster è una delle principali organizzazioni di tecnologia educativa con sede a Skopje, Macedonia del Nord, fondata nel 2015. Attraverso un\'educazione pratica e orientata alle esigenze del mercato, Brainster fornisce alle persone competenze per il futuro nei settori IT, intelligenza artificiale, marketing digitale, design e imprenditorialità. L\'organizzazione ha formato oltre 14.000 studenti e sviluppato soluzioni innovative per l\'apprendimento digitale, tra cui un proprio learning management system e una piattaforma di apprendimento basata sull\'intelligenza artificiale.',
                'Nel progetto RE-MIND, Brainster guida il Work Package 6 dedicato a Comunicazione, Disseminazione e Sostenibilità, coordinando la strategia di comunicazione del progetto, l\'identità visiva, il sito web, i social media e il coinvolgimento degli stakeholder. Brainster contribuisce inoltre allo sviluppo dello Smart Learning Ecosystem, sostenendo il framework per le micro-credenziali e il riconoscimento istituzionale. Grazie alla vasta esperienza nell\'educazione digitale, nelle tecnologie per l\'apprendimento, nelle campagne di comunicazione e nei progetti di cooperazione europea, Brainster contribuisce a garantire un\'ampia visibilità, la sostenibilità a lungo termine e un impatto significativo dei risultati del progetto in tutta Europa.',
            ],
        ],
    ],
];
